### ISSUE TITLE
[Handpicked Matmul Shapes] CUDA Matmul Codgen Performance Profiling in CI 

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#12919] opened 2023-04-04 19:05 UTC
### Request description

In these three problem, we conduct both verification and profiling. If the functionality is compromised or the performance falls below a specified threshold, an alarm is triggered. As performance improvements are made, we can progressively raise the threshold to maintain high standards. Also see #12899 

## 1. Maximize A100 Utilization (`m = 3456`, `n = 1024`, `k = 2048`)

With these dimensions, the matmul operation is optimally tiled using a 128x128 tile size on the A100 GPU, which has 108 SMs. This configuration runs 216 thread blocks, each with a 128x128 thread block tile, ensuring efficient utilization of the A100's resources.

Data type : `f16`
Providers : `IREE Codegen`
Measured IREE codegen performance : `237 TFLOP/s`
Threshold IREE codegen performance : `230 TFLOP/s`

```mlir
func.func @matmul_3456x1024x2048_f16t_f16t_f16t_tile_config_default(
  %lhs: tensor<3456x2048xf16>,
  %rhs: tensor<2048x1024xf16>) -> tensor<3456x1024xf16>
{
  %c0 = arith.constant 0.0 : f16
  %init = tensor.empty() : tensor<3456x1024xf16>
  %inital_result = linalg.fill ins(%c0 : f16) outs(%init : tensor<3456x1024xf16>) -> tensor<3456x1024xf16>
  %result = linalg.matmul  
                     ins(%lhs, %rhs: tensor<3456x2048xf16>, tensor<2048x1024xf16>)
                     outs(%inital_result: tensor<3456x1024xf16>) -> tensor<3456x1024xf16>
  return %result : tensor<3456x1024xf16>
}
```

Data type : `f32`
Providers: `IREE Codegen`
Measured IREE codegen performance : `120 TFLOP/s`
Threshold IREE codegen performance : `115 TFLOP/s`

``` mlir
func.func @matmul_3456x1024x2048_f32t_f32t_f32t_tile_config_default(
  %lhs: tensor<3456x2048xf32>,
  %rhs: tensor<2048x1024xf32>) -> tensor<3456x1024xf32>
{
  %c0 = arith.constant 0.0 : f32
  %init = tensor.empty() : tensor<3456x1024xf32>
  %inital_result = linalg.fill ins(%c0 : f32) outs(%init : tensor<3456x1024xf32>) -> tensor<3456x1024xf32>
  %result = linalg.matmul  
                     ins(%lhs, %rhs: tensor<3456x2048xf32>, tensor<2048x1024xf32>)
                     outs(%inital_result: tensor<3456x1024xf32>) -> tensor<3456x1024xf32>
  return %result : tensor<3456x1024xf32>
}
```

## 2. Square Problem Shape (`m = 2560`, `n = 2560`, `k = 2560` )

For one of the square aligned matrix sizes, we have consistently observed that the 256x128 tile configuration delivers superior performance.

Data type : `f16`
Providers : `IREE Codegen`
Measured IREE codegen performance : `239 TFLOP/s`
Threshold IREE codegen performance : `232 TFLOP/s`

```mlir
func.func @matmul_2560x2560x2560_f16t_f16t_f16t_tile_config_default(
  %lhs: tensor<2560x2560xf16>,
  %rhs: tensor<2560x2560xf16>) -> tensor<2560x2560xf16>
{
  %c0 = arith.constant 0.0 : f16
  %init = tensor.empty() : tensor<2560x2560xf16>
  %inital_result = linalg.fill ins(%c0 : f16) outs(%init : tensor<2560x2560xf16>) -> tensor<2560x2560xf16>
  %result = linalg.matmul  
                     ins(%lhs, %rhs: tensor<2560x2560xf16>, tensor<2560x2560xf16>)
                     outs(%inital_result: tensor<2560x2560xf16>) -> tensor<2560x2560xf16>
  return %result : tensor<2560x2560xf16>
}
```

Data type : `f32`
Providers: `IREE Codegen`
Measured IREE codegen performance : `116 TFLOP/s`
Threshold IREE codegen performance : `110 TFLOP/s`

```mlir
func.func @matmul_2560x2560x2560_f32t_f32t_f32t_tile_config_default(
  %lhs: tensor<2560x2560xf32>,
  %rhs: tensor<2560x2560xf32>) -> tensor<2560x2560xf32>
{
  %c0 = arith.constant 0.0 : f32
  %init = tensor.empty() : tensor<2560x2560xf32>
  %inital_result = linalg.fill ins(%c0 : f32) outs(%init : tensor<2560x2560xf32>) -> tensor<2560x2560xf32>
  %result = linalg.matmul  
                     ins(%lhs, %rhs: tensor<2560x2560xf32>, tensor<2560x2560xf32>)
                     outs(%inital_result: tensor<2560x2560xf32>) -> tensor<2560x2560xf32>
  return %result : tensor<2560x2560xf32>
}
```

## 3. Split-K Friendly Matmul Shape (`m = 128`, `n = 256`, `k = 8192`)
Data type : `f16`
Providers : `IREE Codegen`

```mlir
func.func @matmul_128x256x8192_f16t_f16t_f16t_tile_config_default(
  %lhs: tensor<128x8192xf16>,
  %rhs: tensor<8192x256xf16>) -> tensor<128x256xf16>
{
  %c0 = arith.constant 0.0 : f16
  %init = tensor.empty() : tensor<128x256xf16>
  %inital_result = linalg.fill ins(%c0 : f16) outs(%init : tensor<128x256xf16>) -> tensor<128x256xf16>
  %result = linalg.matmul  
                     ins(%lhs, %rhs: tensor<128x8192xf16>, tensor<8192x256xf16>)
                     outs(%inital_result: tensor<128x256xf16>) -> tensor<128x256xf16>
  return %result : tensor<128x256xf16>
}
```

Data type : `f32`
Providers : `IREE Codegen`

```mlir
func.func @matmul_128x256x8192_f32t_f32t_f32t_tile_config_default(
  %lhs: tensor<128x8192xf32>,
  %rhs: tensor<8192x256xf32>) -> tensor<128x256xf32>
{
  %c0 = arith.constant 0.0 : f32
  %init = tensor.empty() : tensor<128x256xf32>
  %inital_result = linalg.fill ins(%c0 : f32) outs(%init : tensor<128x256xf32>) -> tensor<128x256xf32>
  %result = linalg.matmul  
                     ins(%lhs, %rhs: tensor<128x8192xf32>, tensor<8192x256xf32>)
                     outs(%inital_result: tensor<128x256xf32>) -> tensor<128x256xf32>
  return %result : tensor<128x256xf32>
}
```

**Legend on Tile Configuration Naming** 
The Tile configuration are named with the following naming convention: `tile_config_TileMxTileN_TileKxPipelineStages_CompilePassPipeline`. Consider an example tile config as`tile_config_128x128_32x5_tensorcore_mma_sync`:
- `128x128` is threadblock tile in M and N dimension in number of elements.
- `32` is threadblock tile in the K dimension in number of elements.
- `5` is the number of pipeline of stages.
- `tensor_mma_sync` means CompilePassPipeline of `LLVMGPUMatmulTensorCoreMmaSync`.

**Comment by mariecwhite** [comment] 2023-04-06 03:07
This PR adds the microbenchmarks: https://github.com/openxla/iree/actions/runs/4624853053

I'm getting a compiler issue below. Are we missing the tile configs?:
```
[9/306] Generating /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_matmul_2560x2560x2560_f16t_f16t_f16t_tile_config_256x128_32x3_tensorcore_mmasync_module_c91ccf1fb3086a35cffd2e8bed6be929574a9ba626d9f271f577503ad07e3509/module.vmfb from matmul_2560x2560x2560_f16t_f16t_f16t_tile_config_256x128_32x3_tensorcore_mmasync(linalg) [cuda-sm_80-linux_gnu-cuda][ukernel,matmul]
FAILED: e2e_test_artifacts/iree_matmul_2560x2560x2560_f16t_f16t_f16t_tile_config_256x128_32x3_tensorcore_mmasync_module_c91ccf1fb3086a35cffd2e8bed6be929574a9ba626d9f271f577503ad07e3509/module.vmfb /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_matmul_2560x2560x2560_f16t_f16t_f16t_tile_config_256x128_32x3_tensorcore_mmasync_module_c91ccf1fb3086a35cffd2e8bed6be929574a9ba626d9f271f577503ad07e3509/module.vmfb 
cd /work/build-e2e-test-artifacts/tests/e2e/test_artifacts && /work/full-build-dir/install/bin/iree-compile --output-format=vm-bytecode --iree-hal-target-backends=cuda --iree-input-type=none --iree-hal-cuda-llvm-target-arch=sm_80 --iree-hal-benchmark-dispatch-repeat-count=100 /work/build-e2e-test-artifacts/e2e_test_artifacts/model_81cebaaf-e23d-4a32-89dc-9fc7adc37a8f_matmul_2560x2560x2560_f16t_f16t_f16t_tile_config_256x128_32x3_tensorcore_mmasync.mlir -o /work/build-e2e-test-artifacts/e2e_test_artifacts/iree_matmul_2560x2560x2560_f16t_f16t_f16t_tile_config_256x128_32x3_tensorcore_mmasync_module_c91ccf1fb3086a35cffd2e8bed6be929574a9ba626d9f271f577503ad07e3509/module.vmfb --iree-hal-executable-object-search-path=\"/work/build-e2e-test-artifacts\"
/work/build-e2e-test-artifacts/e2e_test_artifacts/model_81cebaaf-e23d-4a32-89dc-9fc7adc37a8f_matmul_2560x2560x2560_f16t_f16t_f16t_tile_config_256x128_32x3_tensorcore_mmasync.mlir:8:91: error: undefined symbol alias id 'tile_config_256x128_32x3_tensorcore_mmasync'
  %result = linalg.matmul {compilation_info = #tile_config_256x128_32x3_tensorcore_mmasync}
```

**Comment by mariecwhite** [comment] 2023-04-06 12:44
Updated the PR with the right mlir. Results are here: https://gist.github.com/iree-github-actions-bot/53d8ae29ad25b2137667855a2254a86d (search for matmul). Do the latencies look correct?

**Comment by julianwa** [comment] 2023-04-13 02:46
@mariecwhite shared these links to these matmuls on perf.iree.dev:

- https://perf.iree.dev/serie?IREE?8cd75d3e73a3fff5a7d8353eac738cbbb79d37c3472d10ef30da7a72379b1c7b
- https://perf.iree.dev/serie?IREE?e2318cd06989dd3b7e7084e16eceb8c42668f888bbdfb978a3155879f7f97c82
- https://perf.iree.dev/serie?IREE?dfcf2047c19fcbc523314dd9de44268df5dad4a1984ad692e42d81f0201d037f
- https://perf.iree.dev/serie?IREE?be0b8a1c492d625d479b0193684f4721ee7fadd8b7d54f53505a470636bc28b8
- https://perf.iree.dev/serie?IREE?5264eb8fb2de724f31be68b70b39c55b4a1d28fb6914ffa9c0016275d85d95f8
- https://perf.iree.dev/serie?IREE?4f1bbb28c002cdf81aac85dc40b1053b542c54d58840e45b9dd970dc4f803ad1

Can we close this issue now?

**Comment by manishucsd** [comment] 2023-04-13 05:17
Q1. Do we have thresholds on performance regressions that will trigger an alarm on the commit that causes regression OR someone will have to go in check the commit timeline manually to inspect which commit caused the regression? 

Q2. Do we check for functionality for these sizes in these runs?


Also it is tough to track runtime, TFLOP/s will be a better metric to keep track (if possible). I know I have mentioned it a couple of times and it is not possible in the current benchmarking infra, but it will be good to have path to reporting TFLOP/s for performance measurement.

**Comment by pzread** [comment] 2023-04-13 05:28
> Q1. Do we have thresholds on performance regressions that will trigger an alarm on the commit that causes regression OR someone will have to go in check the commit timeline manually to inspect which commit caused the regression?

Right now it works exactly the same as the e2e benchmarks. If people run CUDA benchmarks in PR, it will show the performance change if it's larger than the threshold (by default is 5%, adjustable). Or we need to look into the dashboard to find which commit causes the regression (it shows a data point for each commit, so usually the one jump up is the root cause)

> Q2. Do we check for functionality for these sizes in these runs?

Not yet. Checking the correctness of benchmark runs is a planned work (hopefully we can do it in Q2)

**Closed as completed** 2023-09-28 21:42 UTC
Labels: enhancement ➕, infrastructure/benchmark, benchmarks:cuda
