### ISSUE TITLE
Can not execute from shark_turbine.aot import *

### ISSUE THREAD

**Issue by FlintWangacc** [iree-org/iree#19303] opened 2024-11-26 10:44 UTC
### What happened?

```python
from shark_turbine.aot import *
```
RuntimeError: Only a single TORCH_LIBRARY can be used to register the namespace turbine; please put all of your definitions in a single TORCH_LIBRARY block.  If you were trying to specify implementations, consider using TORCH_LIBRARY_IMPL (which can be duplicated).  If you really intended to define operators for a single namespace in a distributed way, you can use TORCH_LIBRARY_FRAGMENT to explicitly indicate this.  Previous registration of TORCH_LIBRARY was registered at /dev/null:86; latest registration was registered at /dev/null:86               
produce
![Image](https://github.com/user-attachments/assets/59ba7c3d-e4da-42d9-8b1d-0f490ff5f381)

**Comment by ScottTodd** [comment] 2024-11-26 16:07
Duplicate of https://github.com/iree-org/iree/issues/19301

**Closed as not planned by ScottTodd** 2024-11-26 16:07 UTC
Labels: bug 🐞
