### ISSUE TITLE
ONNX Test case failure - add_uint8 - Expected ui8, getting i8

### ISSUE THREAD

**Issue by PhaneeshB** [iree-org/iree#16916] opened 2024-03-27 16:58 UTC
### What happened?

```
Stdout diagnostics:
EXEC @test_add_uint8

[FAILED] result[0]: metadata is 3x4x5xi8; expected that the view matches 3x4x5xui8; expected that the view is equal to contents of a view of 3x4x5xui8

expected:
3x4x5xui8=[[18 24 22 22 20][14 38 44 14 27][30 14 20 12 20][36 25 31 6 8]][[28 30 19 7 18][26 33 23 34 19][29 39 14 32 44][26 25 18 28 24]][[24 36 16 28 25][16 23 22 20 39][27 20 34 19 26][16 17 8 16 11]]
  actual:
3x4x5xi8=[[18 24 22 22 20][14 38 44 14 27][30 14 20 12 20][36 25 31 6 8]][[28 30 19 7 18][26 33 23 34 19][29 39 14 32 44][26 25 18 28 24]][[24 36 16 28 25][16 23 22 20 39][27 20 34 19 26][16 17 8 16 11]]

Compiled with: iree-compile model.mlir --iree-hal-target-backends=llvm-cpu -o model_cpu_llvm_sync_test.vmfb

Run with: iree-run-module --module=model_cpu_llvm_sync_test.vmfb --device=local-sync --flagfile=test_data_flags.txt
 ```
 MLIR :
 ```
 module {
  func.func @test_add_uint8(%arg0: !torch.vtensor<[3,4,5],ui8>, %arg1: !torch.vtensor<[3,4,5],ui8>) -> !torch.vtensor<[3,4,5],ui8> attributes {torch.onnx_meta.ir_version = 7 : si64, torch.onnx_meta.opset_version = 17 : si64, torch.onnx_meta.producer_name = "backend-test", torch.onnx_meta.producer_version = ""} {
    %none = torch.constant.none
    %0 = torch.operator "onnx.Add"(%arg0, %arg1) : (!torch.vtensor<[3,4,5],ui8>, !torch.vtensor<[3,4,5],ui8>) -> !torch.vtensor<[3,4,5],ui8> 
    return %0 : !torch.vtensor<[3,4,5],ui8>
  }
}
 ```
 iree-compiler  and runtime versions : `20240326.843`

**Comment by PhaneeshB** [comment] 2024-03-27 17:00
This issue is an example issue for other multiple related test failing with uint result type 
and also for the sint dtype here https://github.com/openxla/iree/issues/16674

**Comment by ScottTodd** [comment] 2024-03-27 17:06
Duplicate of https://github.com/openxla/iree/issues/16674 (likely the same root cause / not different enough to have a separate issue)

**Closed as not planned by ScottTodd** 2024-03-27 17:06 UTC
Labels: bug 🐞
