### ISSUE TITLE
SPIR-V+MoltenVK on M1 Test failures

### ISSUE THREAD

**Issue by powderluv** [iree-org/iree#8321] opened 2022-02-14 20:35 UTC
Currently vulkan+moltenVK (latest version as of today) fail with 

```The following tests FAILED:
	109 - iree/test/e2e/models/collatz.mlir.test (Failed)
	118 - iree/test/e2e/models/check_vulkan-spirv_vulkan_bert_encoder_unrolled_fake_weights.mlir (Failed)
	122 - iree/test/e2e/regression/libm_linking.mlir.test (Failed)
	599 - iree/compiler/Dialect/HAL/Target/LLVM/test/smoketest.mlir.test (Failed)
```

I am using Top of Master with 

1: https://github.com/google/iree/pull/8295
2: https://github.com/nirvedhmeshram/iree/tree/apple-vulkan

**Comment by benvanik** [comment] 2022-02-14 20:36
(those last two don't touch vulkan/spirv, so unrelated? unless 8295 causes them to fail?)

**Comment by antiagainst** [comment] 2022-02-14 22:45
The last two are separate and they are just failing off the top of the tree right now.

Also, I see more failures on my side. Probably due to that I'm using an old non-M1 macBook here.

**Comment by freedomtan** [comment] 2022-02-17 01:37
FYR. I got same errors with @powderluv on an M1 device.

**Comment by antiagainst** [comment] 2022-09-23 00:56
This has been a while; so closing due to obsolete. (We don't have a mac buildbot; so it's prone to regression..)

**Closed by antiagainst** 2022-09-23 00:56 UTC
Labels: bug 🐞, help wanted, platform/macos 🍎, hal/vulkan, codegen/spirv
