### ISSUE TITLE
`RematerializeParallelOps` appears to enter an infinite loop

### ISSUE THREAD

**Issue by rsuderman** [iree-org/iree#14258] opened 2023-06-28 22:52 UTC
Source IR:
https://gist.github.com/rsuderman/08b1750ed75676e0309f5c8fe84ae970

IR Before the guilty pass:
https://gist.github.com/rsuderman/1ed73adfc4bbed592778e7dae3896d7d

When compiling for `llvm-cpu` the compilation appears to halt completely when executing `RematerializeParallelOps`. Likely the pass is entering an infinite loop.

**Comment by ScottTodd** [comment] 2023-06-28 22:56
Looks like a duplicate of https://github.com/openxla/iree/issues/14245. Good to know it happens for `llvm-cpu` as well.

**Comment by MaheshRavishankar** [comment] 2023-06-29 01:22
Thanks. Will take a look tomorrow. But I might not be able to fix for good before I head out on vacation

**Closed as completed** 2023-06-29 18:47 UTC
Labels: codegen
