### ISSUE TITLE
30% VMVX regression on mobilenet with pipeline changes

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#6742] opened 2021-08-12 15:32 UTC
![image](https://user-images.githubusercontent.com/75337/129219650-c68f6658-e807-43c2-9d75-2aa28b48ae4c.png)
https://perf.iree.dev/serie?IREE?MobileNetV3Small%20[fp32,imagenet]%20(TensorFlow)%203-thread,little-core,full-inference%20with%20IREE-VMVX%20@%20Pixel-4%20(CPU-ARMv8.2-A)

Started with https://github.com/google/iree/pull/6084. It sounds like the pipeline changes were supposed to be NFC but aren't.

mobilenetv3_fake_weights before: https://gist.github.com/benvanik/629fe909b6eadc6f1f2712a9037380be
after: https://gist.github.com/benvanik/d3fb4a83fc1c63c12dc2cef06f227101

There's a lot of smaller changes inside of the executables but the big regression is likely that now we are parallelizing the dispatch workgroups much less, and it makes sense that going from 3 threads to 1 would drop our perf a lot:
![image](https://user-images.githubusercontent.com/75337/129224713-b40da6a5-6f0b-40c1-8336-c48995d39340.png)

The executable changes may be fine (some look like improvements) so it may just be tuning the tiling parameters that's required. Interestingly this may indicate issues that are also present in the dylib case, just showing where we should be tiling much more given the scaling on the total execution time per workgroup in vmvx.

Command to get the above IR (may not all be needed):
```
        "-mlir-elide-elementsattrs-if-larger=8192",
        "-iree-hal-target-backends=vmvx",
        "-iree-vm-target-extension=f32",
        "-iree-abi-transform-pipeline",
        "-canonicalize",
        "-iree-mhlo-input-transformation-pipeline",
        "-iree-flow-transformation-pipeline",
        "-pass-pipeline=iree-hal-transformation-pipeline{serialize-executables=false},canonicalize",
        "${workspaceFolder}/iree/test/e2e/models/mobilenetv3_fake_weights.mlir",
```

**Comment by alliemartens** [comment] 2022-07-07 19:18
@benvanik @MaheshRavishankar Old issue alert! Still active? P1 or P2?

**Comment by MaheshRavishankar** [comment] 2022-07-11 19:23
I think I dropped the ball on this one. Didnt follow up based on regression on my change. Its more than a year old. I'd vote to close it. I cant see the history of this benchmark since then on our dash board though to see if this regression has been convered. Overall there are related issues similar to this one (https://github.com/iree-org/iree/issues/9660 for example is the inverse of this). So there is nothing specific that this bug is needed for.

**Closed** 2022-07-13 16:09 UTC
Labels: performance ⚡, codegen/vmvx
