### ISSUE TITLE
failed to legalize operation 'mhlo.convolution' that was explicitly marked illegal

### ISSUE THREAD

**Issue by sun2011yao** [iree-org/iree#7963] opened 2021-12-28 08:58 UTC
Hi, I use iree-import-tf tool to import stylegan2 tensorflow model, but it failed, the error message is as follows:

<unknown>:0: error: loc(callsite(callsite(fused["conv2d_transpose", "conv2d_transpose@__inference___call___6684"] at fused["StatefulPartitionedCall", "StatefulPartitionedCall@__inference_signature_wrapper_7297"]) at "StatefulPartitionedCall")): failed to legalize operation 'mhlo.convolution' that was explicitly marked illegal
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite(fused["conv2d_transpose", "conv2d_transpose@__inference___call___6684"] at fused["StatefulPartitionedCall", "StatefulPartitionedCall@__inference_signature_wrapper_7297"]) at "StatefulPartitionedCall")): diagnostic emitted with trace:
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):

<unknown>:0: note: loc(callsite(callsite(fused["conv2d_transpose", "conv2d_transpose@__inference___call___6684"] at fused["StatefulPartitionedCall", "StatefulPartitionedCall@__inference_signature_wrapper_7297"]) at "StatefulPartitionedCall")): see current operation: %1884 = "mhlo.convolution"(%1445, %1883) {batch_group_count = 1 : i64, dimension_numbers = #mhlo.conv<[b, 0, 1, f]x[0, 1, i, o]->[b, 0, 1, f]>, feature_group_count = 1 : i64, lhs_dilation = dense<2> : tensor<2xi64>, padding = dense<2> : tensor<2x2xi64>, rhs_dilation = dense<1> : tensor<2xi64>, window_strides = dense<1> : tensor<2xi64>} : (tensor<1x4x4x512xf32>, tensor<3x3x512x512xf32>) -> tensor<1x9x9x512xf32> loc(callsite(callsite(fused["conv2d_transpose", "conv2d_transpose@__inference___call___6684"] at fused["StatefulPartitionedCall", "StatefulPartitionedCall@__inference_signature_wrapper_7297"]) at "StatefulPartitionedCall"))

Run the command as follows:
iree-import-tf \
    --mlir-disable-threading \
  --mlir-print-stacktrace-on-diagnostic \
  --tf-import-type=savedmodel_v1 \
 --tf-savedmodel-exported-names=serving_default \
  --save-temp-tf-input='tf_input.mlir' \
  --mlir-print-stacktrace-on-diagnostic \
  -o=iree_input.mlir stylegan2_model

Thanks a lot!

**Comment by sun2011yao** [comment] 2021-12-28 09:05
The model file always fails to upload, if you need the model file, I can send it to your mailbox

**Comment by sun2011yao** [comment] 2022-01-03 07:22
[    // TODO(suderman): Add proper support for padding + dilation for codegen.](url)

**Comment by sun2011yao** [comment] 2022-01-03 07:33
@hanhanW @MaheshRavishankar 
https://github.com/google/iree/blob/682a9c7bfdf5ca22e4968fa4116ea956ea451159/iree/compiler/InputConversion/MHLO/MHLOToMHLOPreprocessing.cpp#L131

It should be this restriction, can this restriction be relaxed?

**Comment by GMNGeoffrey** [comment] 2022-08-08 21:00
Duplicate of #7999

**Closed by GMNGeoffrey** 2022-08-08 21:00 UTC
Labels: bug 🐞, help wanted, integrations/mhlo
