### ISSUE TITLE
CopyToWorkgroupMemory is duplicated on each thread 

### ISSUE THREAD

**Issue by kaivenlong** [iree-org/iree#7356] opened 2021-10-15 03:00 UTC
In https://github.com/google/iree/blob/main/iree/compiler/Codegen/LLVMGPU/LLVMGPUTileAndDistribute.cpp, the getCopyToWorkgroupMemoryMarker is not added to thread level tiling pattern , thus the same WorkgroupMemory is performed on each thread. On cuda, it leads to high bank conflict.

**Comment by GMNGeoffrey** [comment] 2021-10-15 17:41
Thanks Thomas for grabbing this.

@kaivenlong in the future, please delete any template boilerplate you don't fill out :-) (I edited the original post to remove it)

**Comment by ThomasRaoux** [comment] 2021-10-15 20:46
Based on discord discussion the shared memory workgroup do get distributed.
With the default configuration I see no bank conflicts on shared memory store (see below) and it runs in 262us. 

The problem is mainly how do we pick a good configuration. We have on going work to do search to tune the tile and wg sizes better. I'm closing this bug, feel free to reopen or open a new one if you find other potential performance improvements.

![image](https://user-images.githubusercontent.com/24322263/137550985-95cfd776-59ea-41c4-9dbe-663382cb4acf.png)

**Closed as completed** 2021-10-15 20:46 UTC
Labels: bug 🐞
