### ISSUE TITLE
iree-compile generates empty function for fmaf (RISCV32)

### ISSUE THREAD

**Issue by atvrager** [iree-org/iree#14208] opened 2023-06-23 22:24 UTC
### What happened?

@hcindyl and myself are running a small model that consists of a single softmax layer (1x2xi8), on an rv32im core. At execution time, we noticed that the output doesn't match what's expected. I traced through the execution, and at some point, there's a call to `fmodf` that ends up returning NaN, and then math collapses :)

In the intermediate assembly generated by iree-compile, I do not see any call sites for `fmodf`, but do see many calls to `fmaf` -- and this is also reflected in the dumped IR: `fma` is what we expect, not `fmod`.

In the intermediate assembly, there exists a function definition for `fmaf` with no body, followed by a definition of `fmodf` with a body:

```
	.section	.text.fmaf,"ax",@progbits
	.p2align	2
	.type	fmaf,@function
fmaf:
.Lfunc_begin23:
	.cfi_startproc
.Lfunc_end23:
	.size	fmaf, .Lfunc_end23-fmaf
	.cfi_endproc

	.section	.text.fmodf,"ax",@progbits
	.p2align	2
	.type	fmodf,@function
fmodf:
.Lfunc_begin24:
	.cfi_startproc
	addi	sp, sp, -16
	.cfi_def_cfa_offset 16
	sw	ra, 12(sp)
	sw	s0, 8(sp)
```

It seems like this empty `fmaf` method probably shouldn't exist, and a call out to libm woud be appropriate instead? Any idea what causes this empty method to be generated?

### Steps to reproduce your issue

`iree-compile --mlir-print-ir-after-all -iree-llvmcpu-target-triple=riscv32-pc-linux-elf -iree-llvmcpu-target-cpu=generic-rv32 -iree-llvmcpu-target-cpu-features="+m" -iree-llvmcpu-target-abi=ilp32 person_detection_c_module_static.mlir --iree-llvmcpu-keep-linker-artifacts --iree-hal-target-backends=llvm-cpu --iree-llvmcpu-link-static --iree-llvmcpu-link-embedded=false --iree-hal-dump-executable-intermediates-to=/tmp/iree -o /dev/null`

The MLIR file is available here: https://github.com/atvrager/person_detection_c_module/blob/main/person_detection_c_module_static.mlir

In the same repo (https://github.com/atvrager/person_detection_c_module), I've also included the intermediate assembly, and output from my above iree-compile execution.

### What component(s) does this issue relate to?

Compiler

### Version information

IREE (https://openxla.github.io/iree):
  IREE compiler version (unknown)
  LLVM version 17.0.0git
  Optimized build

cd0d1f11713e48c2b17945520602e7ea9f6498c9

**Comment by hcindyl** [comment] 2023-06-23 22:27
@MaheshRavishankar @benvanik Any thoughts?

**Comment by ScottTodd** [comment] 2023-06-23 22:44
> It seems like this empty `fmaf` method probably shouldn't exist, and a call out to libm woud be appropriate instead? Any idea what causes this empty method to be generated?

We generate self-contained executables that don't rely on libm (using https://github.com/openxla/iree/tree/main/runtime/src/iree/builtins/musl) and are also trying to generate our own vectorizable code for some of those functions (see https://github.com/openxla/iree/issues/12783). Maybe the method appears empty due to how those builtins are linked? https://github.com/openxla/iree/blob/c2e602dff3c8e6999241903e9920a4b4c400771f/compiler/src/iree/compiler/Dialect/HAL/Target/LLVMCPU/LLVMCPUTarget.cpp#L443-L454

> The MLIR file is available here: https://github.com/atvrager/person_detection_c_module/blob/main/person_detection_c_module_static.mlir
> 
> In the same repo (https://github.com/atvrager/person_detection_c_module), I've also included the intermediate assembly, and output from my above iree-compile execution.

Just FYI, you can upload small files to https://gist.github.com/ without needing to create a repository, if you just want to link to them as a reference (vs collaborate on the files with git).

**Comment by hcindyl** [comment] 2023-06-23 22:49
We use `--iree-llvmcpu-link-static --iree-llvmcpu-link-embedded=false` to generate the static library object that doesn't use musl libm codegen path (I confirmed with @MaheshRavishankar yesterday on that). We want the program has a clear `.text` and `.data` so the dispatch workload is not embedded in `.data` (also to make the final baremetal program smaller).

**Comment by hcindyl** [comment] 2023-06-23 23:49
Also ping @dcaballe since it can be a RISCV llvm td mapping issue (not use f-ext to lower `llvm.fma`)

**Comment by MaheshRavishankar** [comment] 2023-06-26 17:41
It might be some linking error on the RISC-V backend. It would be good to get the output with `iree-hal-dump-executable-intermediates-to=<tmp_folder>`. It will get the `.bc` files from LLVM. Can you upload the `llvm-dis <..>.bc` files somewhere?```

**Comment by atvrager** [comment] 2023-06-26 18:18
@MaheshRavishankar I've added the bc files from my run into the repo with the other artifacts: https://github.com/atvrager/person_detection_c_module/commit/868d5297061f56fefdf82380fe735200648bb4af

**Comment by MaheshRavishankar** [comment] 2023-06-26 19:21
> @MaheshRavishankar I've added the bc files from my run into the repo with the other artifacts: [atvrager/person_detection_c_module@868d529](https://github.com/atvrager/person_detection_c_module/commit/868d5297061f56fefdf82380fe735200648bb4af)

Sorry, but could you add the *.ll files instead after running `llvm-dis` on them?

**Comment by atvrager** [comment] 2023-06-26 19:38
@MaheshRavishankar no problem! Added *.ll in https://github.com/atvrager/person_detection_c_module/commit/287a813e9f2fd620b2fe995db706c4b73f2aa370

**Comment by allieculp** [comment] 2023-06-29 22:01
Assigning to @dcaballe and @MaheshRavishankar for now, please re-route as needed.

**Comment by MaheshRavishankar** [comment] 2023-06-29 22:05
Actually I have a fix already. I need it to be reviewed to land it.

**Comment by allieculp** [comment] 2023-07-14 18:38
@MaheshRavishankar Can you add the fix here? Is this landed?

**Closed as completed** 2023-07-24 20:43 UTC
Labels: bug 🐞, codegen/riscv
