### ISSUE TITLE
Dynamic stack allocations surviving in inner loops to runtime, causing 💀 

### ISSUE THREAD

**Issue by benvanik** [iree-org/iree#11880] opened 2023-01-18 03:13 UTC
While trying to fix our stack size in #11867 I found that posenet and efficientnet in our integrations tests were failing with anything but 512KB of stack. That's a lot of stack and surprising to me as the model itself barely has any tensors that are that size. Looking through the IR produced it looks like instead of the stack allocation getting hoisted it ends up on the innermost loop. Because [LLVM's alloca](https://llvm.org/docs/LangRef.html#alloca-instruction) by default has function lifetime this means each loop iteration we're allocating more stack space and whether it blows the stack is dependent on the stack size and the shapes used by the model.

```mlir
// -----// IR Dump After EmptyTensorToAllocTensor (empty-tensor-to-alloc-tensor) //----- //
module {
  func.func @main_dispatch_18_matmul_2304x144x24() {
    ...
    %6 = affine.apply affine_map<()[s0] -> (s0 * 256)>()[%workgroup_id_y]
    %7 = affine.apply affine_map<()[s0] -> (s0 * 256)>()[%workgroup_count_y]
    %8 = affine.apply affine_map<()[s0] -> (s0 * 72)>()[%workgroup_id_x]
    %9 = affine.apply affine_map<()[s0] -> (s0 * 72)>()[%workgroup_count_x]
    scf.for %arg0 = %6 to %c2304 step %7 {
      %10 = flow.dispatch.tensor.load %0, offsets = [%arg0, 0], sizes = [256, 24], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<2304x24xi8>> -> tensor<256x24xi8>
      scf.for %arg1 = %8 to %c144 step %9 {
        %11 = flow.dispatch.tensor.load %5, offsets = [%arg0, %arg1], sizes = [256, 72], strides = [1, 1] : !flow.dispatch.tensor<writeonly:tensor<2304x144xi8>> -> tensor<256x72xi8>
        %12 = flow.dispatch.tensor.load %2, offsets = [%arg1], sizes = [72], strides = [1] : !flow.dispatch.tensor<readonly:tensor<144xi32>> -> tensor<72xi32>
        %13 = flow.dispatch.tensor.load %1, offsets = [0, %arg1], sizes = [24, 72], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<24x144xi8>> -> tensor<24x72xi8>
        %14 = flow.dispatch.tensor.load %3, offsets = [%arg1], sizes = [72], strides = [1] : !flow.dispatch.tensor<readonly:tensor<144xi32>> -> tensor<72xi32>
        %15 = flow.dispatch.tensor.load %4, offsets = [%arg1], sizes = [72], strides = [1] : !flow.dispatch.tensor<readonly:tensor<144xi32>> -> tensor<72xi32>
        %extracted_slice = tensor.extract_slice %cst[%arg1] [72] [1] : tensor<144xi8> to tensor<72xi8>
        %16 = scf.for %arg2 = %c0 to %c256 step %c8 iter_args(%arg3 = %11) -> (tensor<256x72xi8>) {
          %extracted_slice_0 = tensor.extract_slice %10[%arg2, 0] [8, 24] [1, 1] : tensor<256x24xi8> to tensor<8x24xi8>
          %17 = scf.for %arg4 = %c0 to %c72 step %c32 iter_args(%arg5 = %arg3) -> (tensor<256x72xi8>) {
            %18 = affine.min affine_map<(d0) -> (-d0 + 72, 32)>(%arg4)
            %extracted_slice_1 = tensor.extract_slice %12[%arg4] [%18] [1] : tensor<72xi32> to tensor<?xi32>
            %extracted_slice_2 = tensor.extract_slice %13[0, %arg4] [24, %18] [1, 1] : tensor<24x72xi8> to tensor<24x?xi8>
            %19 = bufferization.alloc_tensor(%18) : tensor<8x?xi32>
            %20 = linalg.fill ins(%c0_i32 : i32) outs(%19 : tensor<8x?xi32>) -> tensor<8x?xi32>
```

```mlir
// -----// IR Dump After IREEComprehensiveBufferize (iree-codegen-iree-comprehensive-bufferize) //----- //
module {
  func.func @main_dispatch_18_matmul_2304x144x24() {
    ...
    %13 = affine.apply affine_map<()[s0] -> (s0 * 256)>()[%workgroup_id_y]
    %14 = affine.apply affine_map<()[s0] -> (s0 * 256)>()[%workgroup_count_y]
    %15 = affine.apply affine_map<()[s0] -> (s0 * 72)>()[%workgroup_id_x]
    %16 = affine.apply affine_map<()[s0] -> (s0 * 72)>()[%workgroup_count_x]
    scf.for %arg0 = %13 to %c2304 step %14 {
      %subview = memref.subview %1[%arg0, 0] [256, 24] [1, 1] : memref<2304x24xi8, #hal.descriptor_type<storage_buffer>> to memref<256x24xi8, strided<[24, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>
      scf.for %arg1 = %15 to %c144 step %16 {
        %subview_0 = memref.subview %11[%arg0, %arg1] [256, 72] [1, 1] : memref<2304x144xi8, #hal.descriptor_type<storage_buffer>> to memref<256x72xi8, strided<[144, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>
        %subview_1 = memref.subview %5[%arg1] [72] [1] : memref<144xi32, #hal.descriptor_type<storage_buffer>> to memref<72xi32, strided<[1], offset: ?>, #hal.descriptor_type<storage_buffer>>
        %subview_2 = memref.subview %3[0, %arg1] [24, 72] [1, 1] : memref<24x144xi8, #hal.descriptor_type<storage_buffer>> to memref<24x72xi8, strided<[144, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>
        %subview_3 = memref.subview %7[%arg1] [72] [1] : memref<144xi32, #hal.descriptor_type<storage_buffer>> to memref<72xi32, strided<[1], offset: ?>, #hal.descriptor_type<storage_buffer>>
        %subview_4 = memref.subview %9[%arg1] [72] [1] : memref<144xi32, #hal.descriptor_type<storage_buffer>> to memref<72xi32, strided<[1], offset: ?>, #hal.descriptor_type<storage_buffer>>
        %subview_5 = memref.subview %0[%arg1] [72] [1] : memref<144xi8> to memref<72xi8, strided<[1], offset: ?>>
        %17 = scf.for %arg2 = %c0 to %c256 step %c8 iter_args(%arg3 = %subview_0) -> (memref<256x72xi8, strided<[144, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>) {
          %subview_7 = memref.subview %subview[%arg2, 0] [8, 24] [1, 1] : memref<256x24xi8, strided<[24, 1], offset: ?>, #hal.descriptor_type<storage_buffer>> to memref<8x24xi8, strided<[24, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>
          %18 = scf.for %arg4 = %c0 to %c72 step %c32 iter_args(%arg5 = %arg3) -> (memref<256x72xi8, strided<[144, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>) {
            %19 = affine.min affine_map<(d0) -> (-d0 + 72, 32)>(%arg4)
            %subview_8 = memref.subview %subview_1[%arg4] [%19] [1] : memref<72xi32, strided<[1], offset: ?>, #hal.descriptor_type<storage_buffer>> to memref<?xi32, strided<[1], offset: ?>, #hal.descriptor_type<storage_buffer>>
            %subview_9 = memref.subview %subview_2[0, %arg4] [24, %19] [1, 1] : memref<24x72xi8, strided<[144, 1], offset: ?>, #hal.descriptor_type<storage_buffer>> to memref<24x?xi8, strided<[144, 1], offset: ?>, #hal.descriptor_type<storage_buffer>>
            %alloca = memref.alloca(%19) {alignment = 64 : i64} : memref<8x?xi32>
```

```mlir

```mlir
        llvm.func @main_dispatch_18_matmul_2304x144x24(%arg0: !llvm.ptr<struct<"iree_hal_executable_environment_v0_t", (ptr<i32>, ptr<func<i32 (ptr<func<i32 (ptr<i8>, ptr<i8>, ptr<i8>)>>, ptr<i8>, ptr<i8>, ptr<i8>)>>, ptr<ptr<func<i32 (ptr<i8>, ptr<i8>, ptr<i8>)>>>, ptr<ptr<i8>>, struct<"iree_hal_processor_v0_t", (array<8 x i64>)>)>> {llvm.align = 16 : i64, llvm.noalias}, %arg1: !llvm.ptr<struct<"iree_hal_executable_dispatch_state_v0_t", (i32, i32, i16, i16, i32, i32, i16, i8, i8, ptr<i32>, ptr<ptr<i8>>, ptr<i64>)>> {llvm.align = 16 : i64, llvm.noalias}, %arg2: !llvm.ptr<struct<"iree_hal_executable_workgroup_state_v0_t", (i32, i32, i16, i16, i32, ptr<ptr<i8>>, i32)>> {llvm.align = 16 : i64, llvm.noalias}) -> i32 {
          ...
          %75 = llvm.mul %74, %5  : i64
          %76 = llvm.mul %74, %4  : i64
          %77 = llvm.mul %72, %14  : i64
          %78 = llvm.add %76, %77  : i64
          llvm.br ^bb1(%15 : i64)
        ^bb1(%79: i64):  // 2 preds: ^bb0, ^bb25
          %80 = llvm.icmp "slt" %79, %13 : i64
          llvm.cond_br %80, ^bb2, ^bb26
        ^bb2:  // pred: ^bb1
          %81 = llvm.mul %79, %10  : i64
          %82 = llvm.add %75, %81  : i64
          llvm.br ^bb3(%15 : i64)
        ^bb3(%83: i64):  // 2 preds: ^bb2, ^bb24
          %84 = llvm.icmp "slt" %83, %14 : i64
          llvm.cond_br %84, ^bb4, ^bb25
        ^bb4:  // pred: ^bb3
          %85 = llvm.mul %83, %3  : i64
          %86 = llvm.add %85, %14  : i64
          %87 = llvm.icmp "slt" %86, %12 : i64
          %88 = llvm.select %87, %86, %12 : i1, i64
          %89 = llvm.add %77, %83  : i64
          %90 = llvm.mul %88, %11  : i64
          %91 = llvm.mlir.null : !llvm.ptr<i32>
          %92 = llvm.getelementptr %91[%90] : (!llvm.ptr<i32>, i64) -> !llvm.ptr<i32>
          %93 = llvm.ptrtoint %92 : !llvm.ptr<i32> to i64
          %94 = llvm.alloca %93 x i32 {alignment = 64 : i64} : (i64) -> !llvm.ptr<i32>
```

The two tflite models I noticed exhibiting this:
https://storage.googleapis.com/iree-model-artifacts/tflite-integration-tests/posenet_i8.tflite
https://storage.googleapis.com/iree-model-artifacts/efficientnet_lite0_int8_2.tflite

I passed those through pre-release `iree-import-tflite` and then `iree-compile` with https://reviews.llvm.org/D141981 applied (as otherwise they can't compile at head),

**Comment by benvanik** [comment] 2023-01-18 04:02
Here's one of the executables:
```mlir
#map = affine_map<(d0) -> (d0)>
#map1 = affine_map<(d0, d1) -> (d1, d0)>
#map2 = affine_map<(d0, d1) -> (d0)>
#map3 = affine_map<(d0, d1, d2, d3) -> (d3)>
#map4 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map5 = affine_map<(d0, d1) -> (d1)>
#map6 = affine_map<(d0, d1) -> (d0, d1)>
#map7 = affine_map<(d0) -> ()>
#map8 = affine_map<(d0, d1) -> ()>
#map9 = affine_map<() -> ()>
#map10 = affine_map<(d0, d1) -> (d0 + d1 * 2)>
  flow.executable private @main_dispatch_18 {
    flow.executable.export public @main_dispatch_18_matmul_2304x144x24 workgroups(%arg0: index, %arg1: index) -> (index, index, index) {
      %x, %y, %z = flow.dispatch.workgroup_count_from_dag_root %arg0, %arg1
      flow.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @main_dispatch_18_matmul_2304x144x24(%arg0: !flow.dispatch.tensor<readonly:tensor<2304x24xi8>>, %arg1: !flow.dispatch.tensor<readonly:tensor<24x144xi8>>, %arg2: !flow.dispatch.tensor<readonly:tensor<144xi32>>, %arg3: !flow.dispatch.tensor<readonly:tensor<144xi32>>, %arg4: !flow.dispatch.tensor<readonly:tensor<144xi32>>, %arg5: !flow.dispatch.tensor<writeonly:tensor<2304x144xi8>>) {
        %c0_i32 = arith.constant 0 : i32
        %c12_i32 = arith.constant 12 : i32
        %c-128_i32 = arith.constant -128 : i32
        %c127_i32 = arith.constant 127 : i32
        %cst = arith.constant dense_resource<__elided__> : tensor<144xi8>
        %0 = flow.dispatch.tensor.load %arg0, offsets = [0, 0], sizes = [2304, 24], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<2304x24xi8>> -> tensor<2304x24xi8>
        %1 = flow.dispatch.tensor.load %arg1, offsets = [0, 0], sizes = [24, 144], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<24x144xi8>> -> tensor<24x144xi8>
        %2 = flow.dispatch.tensor.load %arg2, offsets = [0], sizes = [144], strides = [1] : !flow.dispatch.tensor<readonly:tensor<144xi32>> -> tensor<144xi32>
        %3 = flow.dispatch.tensor.load %arg3, offsets = [0], sizes = [144], strides = [1] : !flow.dispatch.tensor<readonly:tensor<144xi32>> -> tensor<144xi32>
        %4 = flow.dispatch.tensor.load %arg4, offsets = [0], sizes = [144], strides = [1] : !flow.dispatch.tensor<readonly:tensor<144xi32>> -> tensor<144xi32>
        %5 = tensor.empty() : tensor<2304x144xi8>
        %6 = tensor.empty() : tensor<2304x144xi32>
        %7 = linalg.fill ins(%c0_i32 : i32) outs(%6 : tensor<2304x144xi32>) -> tensor<2304x144xi32>
        %8 = linalg.matmul ins(%0, %1 : tensor<2304x24xi8>, tensor<24x144xi8>) outs(%7 : tensor<2304x144xi32>) -> tensor<2304x144xi32>
        %9 = linalg.generic {indexing_maps = [#map5, #map6, #map5, #map5, #map5, #map6], iterator_types = ["parallel", "parallel"]} ins(%2, %8, %3, %4, %cst : tensor<144xi32>, tensor<2304x144xi32>, tensor<144xi32>, tensor<144xi32>, tensor<144xi8>) outs(%5 : tensor<2304x144xi8>) {
        ^bb0(%in: i32, %in_0: i32, %in_1: i32, %in_2: i32, %in_3: i8, %out: i8):
          %10 = arith.muli %in_1, %c12_i32 : i32
          %11 = arith.subi %in_0, %10 : i32
          %12 = arith.addi %in, %11 : i32
          %13 = "tosa.apply_scale"(%12, %in_2, %in_3) {double_round = true} : (i32, i32, i8) -> i32
          %14 = arith.addi %13, %c-128_i32 : i32
          %15 = arith.cmpi slt, %14, %c-128_i32 : i32
          %16 = arith.select %15, %c-128_i32, %14 : i32
          %17 = arith.cmpi sgt, %14, %c127_i32 : i32
          %18 = arith.select %17, %c127_i32, %16 : i32
          %19 = arith.trunci %18 : i32 to i8
          linalg.yield %19 : i8
        } -> tensor<2304x144xi8>
        flow.dispatch.tensor.store %9, %arg5, offsets = [0, 0], sizes = [2304, 144], strides = [1, 1] : tensor<2304x144xi8> -> !flow.dispatch.tensor<writeonly:tensor<2304x144xi8>>
        return
      }
    }
  }
```

**Comment by MaheshRavishankar** [comment] 2023-01-18 07:39
Thanks Ben, so looking at the codegen it seems like this dispatch is actually not vectorized (which is why there is a stack allocation). Looking through the history, tracked it down to this change
https://github.com/llvm/llvm-project/commit/72fd36448d7c97c9dab094d6deda401d97baf0ef#diff-be7661e240d890a641a87f194bbb12e84a340b4a7f408865d5b89082123e24fbR1095

At Line 1095, the initial state that is being checked returns false and vectorization fails. @dcaballe any idea whats happening here. I think fixing that should make the stack go away.

Ill work on a change to make our checks more robust (plus bufferization change to insert end of scope though that will be a bit more involved).

**Comment by MaheshRavishankar** [comment] 2023-01-18 07:58
Moving to @dcaballe for now....

**Comment by dcaballe** [comment] 2023-01-19 01:40
This seems to be a side effect of fusing matmul with its consumers. The test provided has partially dynamic shapes (e.g., `tensor<8x?xi32>`) and it goes through the matmul pipeline so no padding/peeling applied. Masking only supports fully dynamic cases so it fails to vectorize. It can take me a week or two to enable masking for this. Would that work?

**Comment by benvanik** [comment] 2023-01-19 01:58
Sounds like that'd be the right solution - to relieve some pressure on you is there any workaround you see in the interim that isn't just as much work as the right thing? We're currently crashing on some platforms and succeeding by chance on others based on user inputs so it'd be nice to get to a correct/stable state even if it means a performance hit until the proper fix can be made. If we could apply the workaround then we could add the check Mahesh has mentioned that ensures we have no dynamic stack allocations and make it easier to verify the proper fixes work across the zoos.

**Comment by MaheshRavishankar** [comment] 2023-01-19 03:51
I dont think we need padding/peeling. I think this used to work before the masking changes.... I think the vector size chose is 8x32 for the i and j loops. Issue is that 32 doesnt divide 144. WIthout masking/peeling/padding/etc. we would need to ensure that the tile size divides problem size. That seems to have changed (I believe unintentionally) when the masking change landed (let me know if that is wrong). So I would try to get back to the original state (I think the tile size for vectorization was 8x16 which divides the problem size). With that the problem should go away.

@dcaballe what you are suggesting is probably true long term, but this is a regression for now till the complete solution can take its place.

**Comment by dcaballe** [comment] 2023-01-19 06:42
Part of the masking work landed last year so I may have some memory gaps but I'm almost certain that I haven't changed anything related to tile size selection or the vectorization pre-processing strategy in IREE, to the point that the element-wise cases I'm currently enabling masking for have padding enabled and the tile size for vectorization is set to 1! Changes impacting matmuls are even less likely as we use `DoubleTilingPadExpert` by default for x86 for them.

This is what I can see in the debug information:

```
[kernel-dispatch] Vector pre-processing strategy: Padding
[kernel-dispatch] Matmul workgroup sizes: 8 32 16
[kernel-dispatch] Vector pre-processing strategy: Padding
[kernel-dispatch] Flow tile sizes: 256 72 0
[kernel-dispatch] Workgroup tile sizes: 8 32 16
[kernel-dispatch] Vector size: 4
```

So padding is enabled for this case but it doesn't kick in because it's not supported for dynamic shapes, IIRC. @hanhanW can confirm that. I moved the repo back to January 6th and December 1st and the reproducer is not vectorized either and the debug information is identical...

A quick short-term workaround would be to enable peeling for matmuls with dynamic shapes. I should be able to remove that in a few weeks.

**Comment by MaheshRavishankar** [comment] 2023-01-19 17:09
I dont think enabling peeling for matmuls with dynamic shape is necessarily short term. I see it as long term.... I am saying that the tile sizes you are seeing are not what they were.

**Comment by MaheshRavishankar** [comment] 2023-01-20 23:30
Adding @hanhanW as well. It seems like the matmul pad + hoist is not kicking in for i8 types. This is resulting the alloc not being static.

I am planning to strengthen the compile time check to only allow buffers of static shape in the entry block. Thats the only way to ensure static bounded allocations.

**Comment by hanhanW** [comment] 2023-01-30 09:06
It should go with padding approach. The padding approach works for all dynamic cases.

I looked into the IR and found that the padding does not work for i8xi8->i32 because extract_slice(empty) could be folded into a single empty op, which blocks boundary computation. I have a local patch that enhances the padding pattern, and will send it out for review.

**Comment by hanhanW** [comment] 2023-02-01 03:27
https://reviews.llvm.org/D143043 can fix the issue

**Comment by MaheshRavishankar** [comment] 2023-02-01 03:37
Thats great, but we shouldnt be padding an empty tensor. Do you know why that is happening?

**Comment by benvanik** [comment] 2023-02-01 03:49
Good point - isn't a padded empty tensor just a slightly larger emtpty tensor? :P

**Comment by hanhanW** [comment] 2023-02-01 03:58
The IREE ConvertToDPSPass does not convert the tensor.empty op into a `flow.dispatch.tensor.load` because the types mismatch. Because we can't reuse the destination buffer for quantized cases. In this case, there are tensor.empty ops.

Tiling introduces an affine_min op to clamp it within the bound, e.g.,

```
%20 = affine.min affine_map<(d0) -> (-d0 + 72, 32)>(%arg4)
%21 = tensor.empty(%20) : tensor<8x?xi32>
```

We should pad it to a static shape. The smallest bounded size is `32` in this case, which is the tiling size. This is the cost for padding approach. We allocate a small stack buffer for handling in-complete tiles in padding approach.

**Comment by MaheshRavishankar** [comment] 2023-02-01 07:32
Only concern here is that we are padding a tensor that is empty. So there are parts of the tensor that has effectively undef values...

**Comment by hanhanW** [comment] 2023-02-09 01:39
> Only concern here is that we are padding a tensor that is empty. So there are parts of the tensor that has effectively undef values...

It is fine in this case because it will be filled into zeros immediately.

**Closed** 2023-02-16 00:21 UTC
Labels: bug 🐞, codegen/llvm
