### ISSUE TITLE
CI lint failure: bazel_to_cmake.py truncating output CMakeLists.txt at 16,384 bytes.

### ISSUE THREAD

**Issue by bjacob** [iree-org/iree#19365] opened 2024-12-04 03:51 UTC
CI Lint failure:
https://github.com/iree-org/iree/actions/runs/12152435419/job/33888833753?pr=19363.

The failure is that after running bazel_to_cmake.py, the resulting file tests/e2e/stablehlo_ops/CMakeLists.txt was truncated at exactly 16384 bytes ( == 2^14).

As a result it complains of a CMakeLists.txt mismatch:

```diff
--- a/tests/e2e/stablehlo_ops/CMakeLists.txt
+++ b/tests/e2e/stablehlo_ops/CMakeLists.txt
@@ -769,17 +769,4 @@ iree_check_single_backend_test_suite(
     "slice.mlir"
     "sort.mlir"
     "sqrt.mlir"
-    "subtract.mlir"
-    "tanh.mlir"
-    "three_fry.mlir"
-    "torch_index_select.mlir"
-    "transpose.mlir"
-    "while.mlir"
-  TARGET_BACKEND
-    "rocm"
-  # Only test compilation for now, the ROCm driver is experimental.
-  # DRIVER
-  #   "rocm"
-  COMPILER_FLAGS
-    "--iree-input-type=stablehlo"
-)
+    "su
\ No newline at end of file
```

That diff is truncating the file after the first two letters of `"subtract.mlir"`. I tried locally, the resulting truncated file is exactly 16,384 bytes.

**Comment by bjacob** [comment] 2024-12-04 03:52
Another PR based on the same `main` branch commit, is unaffected: https://github.com/iree-org/iree/pull/19364

**Comment by ScottTodd** [comment] 2024-12-04 05:24
Duplicate of https://github.com/iree-org/iree/issues/18014

**Closed as not planned by ScottTodd** 2024-12-04 05:24 UTC
Labels: bug 🐞, infrastructure
