### ISSUE TITLE
[CPU] Unable to resolve all strided buffer descriptors when compiling Llama with dynamic input and data-tiling+microkernels

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#15076] opened 2023-09-30 21:47 UTC
### What happened?

```
gsutil cp gs://iree-model-artifacts/pytorch/manual/llama_linalg_dynamic_zeroed_weights_1696101737.mlir /tmp

./iree-compile --output-format=vm-bytecode --iree-hal-target-backends=llvm-cpu --iree-input-type=none --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu --iree-llvmcpu-target-cpu=cascadelake --iree-opt-data-tiling --iree-llvmcpu-enable-microkernels /tmp/llama_linalg_dynamic_zeroed_weights_1696101737.mlir -o /tmp/module.vmfb
```

Results in error:
```
/tmp/llama_linalg_dynamic_zeroed_weights_1696101737.mlir:521:11: error: Unable to resolve all strided buffer descriptors:
    %52 = linalg.batch_matmul ins(%48, %50 : tensor<1x?x4096xf32>, tensor<1x4096x4096xf32>) outs(%51 : tensor<1x?x4096xf32>) -> tensor<1x?x4096xf32>
          ^
/tmp/llama_linalg_dynamic_zeroed_weights_1696101737.mlir:27:3: note: called from
  func.func @forward(%arg0: tensor<1x?xi64>) -> tensor<1x?x32000xf32> {
  ^
/tmp/llama_linalg_dynamic_zeroed_weights_1696101737.mlir:521:11: note: see current operation: 
"func.func"() <{function_type = () -> (), sym_name = "forward_dispatch_6_batch_mmt4d_1x1x256x4096x16x16x1_f32"}> ({
  %0 = "arith.constant"() <{value = 0 : index}> : () -> index
  %1 = "arith.constant"() <{value = 65536 : index}> : () -> index
  %2 = "arith.constant"() <{value = 32 : index}> : () -> index
  %3 = "arith.constant"() <{value = 4096 : index}> : () -> index
  %4 = "arith.constant"() <{value = 16 : i32}> : () -> i32
  %5 = "arith.constant"() <{value = 1 : i32}> : () -> i32
  %6 = "arith.constant"() <{value = 1025 : i32}> : () -> i32
  %7 = "arith.constant"() <{value = 256 : index}> : () -> index
  %8 = "arith.constant"() <{value = 1 : index}> : () -> index
  %9 = "arith.constant"() <{value = 32 : i64}> : () -> i64
  %10 = "hal.interface.constant.load"() {index = 0 : index} : () -> i32
  %11 = "hal.interface.constant.load"() {index = 1 : index} : () -> i32
  %12 = "hal.interface.constant.load"() {index = 2 : index} : () -> i32
  %13 = "hal.interface.constant.load"() {index = 3 : index} : () -> i32
  %14 = "arith.extui"(%10) : (i32) -> i64
  %15 = "arith.extui"(%11) : (i32) -> i64
  %16 = "arith.shli"(%15, %9) : (i64, i64) -> i64
  %17 = "arith.ori"(%14, %16) : (i64, i64) -> i64
  %18 = "arith.index_castui"(%17) : (i64) -> index
  %19 = "arith.extui"(%12) : (i32) -> i64
  %20 = "arith.extui"(%13) : (i32) -> i64
...
```

### Steps to reproduce your issue

```
gsutil cp gs://iree-model-artifacts/pytorch/manual/llama_linalg_dynamic_zeroed_weights_1696101737.mlir /tmp

./iree-compile --output-format=vm-bytecode --iree-hal-target-backends=llvm-cpu --iree-input-type=none --iree-llvmcpu-target-triple=x86_64-unknown-linux-gnu --iree-llvmcpu-target-cpu=cascadelake --iree-opt-data-tiling --iree-llvmcpu-enable-microkernels /tmp/llama_linalg_dynamic_zeroed_weights_1696101737.mlir -o /tmp/module.vmfb
```

### What component(s) does this issue relate to?

Compiler

### Version information

0af63addc

**Comment by pzread** [comment] 2023-10-03 15:31
The model link seems to be moved to https://storage.googleapis.com/iree-model-artifacts/pytorch/manual/llama1_prefill_linalg_dynamic_zeroed_weights_1696101737.mlir

**Comment by qcolombet** [comment] 2023-10-04 09:41
Smaller reproducer:
```mlir
module {
  func.func private @iree_uk_mmt4d(memref<f32>, index, index, memref<f32>, index, index, memref<f32>, index, index, index, index, index, i32, i32, i32, i32) attributes {hal.import.bitcode = true, hal.import.cconv = 1 : i32, hal.import.fields = ["processor_data"], llvm.bareptr = true}
  func.func @forward_dispatch_6_batch_mmt4d_1x1x256x4096x16x16x1_f32() {
    %c65536 = arith.constant 65536 : index
    %c32 = arith.constant 32 : index
    %c4096 = arith.constant 4096 : index
    %c16_i32 = arith.constant 16 : i32
    %c1_i32 = arith.constant 1 : i32
    %c1025_i32 = arith.constant 1025 : i32
    %c256 = arith.constant 256 : index
    %c1 = arith.constant 1 : index
    %c32_i64 = arith.constant 32 : i64
    %c0 = arith.constant 0 : index
    %0 = hal.interface.constant.load[0] : i32
    %1 = hal.interface.constant.load[1] : i32
    %2 = hal.interface.constant.load[2] : i32
    %3 = hal.interface.constant.load[3] : i32
    %4 = arith.extui %0 : i32 to i64
    %5 = arith.extui %1 : i32 to i64
    %6 = arith.shli %5, %c32_i64 : i64
    %7 = arith.ori %4, %6 : i64
    %8 = arith.index_castui %7 : i64 to index
    %9 = arith.extui %2 : i32 to i64
    %10 = arith.extui %3 : i32 to i64
    %11 = arith.shli %10, %c32_i64 : i64
    %12 = arith.ori %9, %11 : i64
    %13 = arith.index_castui %12 : i64 to index
    %14 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<1x256x4096x16x1xf32>
    memref.assume_alignment %14, 64 : memref<1x256x4096x16x1xf32>
    %15 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) : memref<1x1x256x16x16xf32>
    memref.assume_alignment %15, 64 : memref<1x1x256x16x16xf32>
    %16 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%8) flags(ReadOnly) : memref<1x?x4096x16x1xf32, strided<[?, 65536, 16, 1, 1], offset: ?>>{%13}
    memref.assume_alignment %16, 1 : memref<1x?x4096x16x1xf32, strided<[?, 65536, 16, 1, 1], offset: ?>>
    %cast = memref.cast %16 : memref<1x?x4096x16x1xf32, strided<[?, 65536, 16, 1, 1], offset: ?>> to memref<1x1x4096x16x1xf32, strided<[?, 65536, 16, 1, 1], offset: ?>>
    %workgroup_id_x = hal.interface.workgroup.id[0] : index
    %workgroup_count_x = hal.interface.workgroup.count[0] : index
    %workgroup_id_y = hal.interface.workgroup.id[1] : index
    %workgroup_count_y = hal.interface.workgroup.count[1] : index
    %workgroup_id_z = hal.interface.workgroup.id[2] : index
    %workgroup_count_z = hal.interface.workgroup.count[2] : index
    scf.for %arg0 = %workgroup_id_z to %c1 step %workgroup_count_z {
      scf.for %arg1 = %workgroup_id_y to %c1 step %workgroup_count_y {
        %17 = affine.apply affine_map<()[s0] -> (s0 * 32)>()[%workgroup_id_x]
        %18 = affine.apply affine_map<()[s0] -> (s0 * 32)>()[%workgroup_count_x]
        scf.for %arg2 = %17 to %c256 step %18 {
          %subview = memref.subview %15[%arg0, %arg1, %arg2, 0, 0] [1, 1, 32, 16, 16] [1, 1, 1, 1, 1] : memref<1x1x256x16x16xf32> to memref<1x1x32x16x16xf32, strided<[65536, 65536, 256, 16, 1], offset: ?>>
          %subview_0 = memref.subview %14[%arg0, %arg2, 0, 0, 0] [1, 32, 4096, 16, 1] [1, 1, 1, 1, 1] : memref<1x256x4096x16x1xf32> to memref<1x32x4096x16x1xf32, strided<[16777216, 65536, 16, 1, 1], offset: ?>>
          %subview_1 = memref.subview %subview[0, 0, 0, 0, 0] [1, 1, 32, 16, 16] [1, 1, 1, 1, 1] : memref<1x1x32x16x16xf32, strided<[65536, 65536, 256, 16, 1], offset: ?>> to memref<1x32x16x16xf32, strided<[65536, 256, 16, 1], offset: ?>>
          %subview_2 = memref.subview %cast[%arg0, %arg1, 0, 0, 0] [1, 1, 4096, 16, 1] [1, 1, 1, 1, 1] : memref<1x1x4096x16x1xf32, strided<[?, 65536, 16, 1, 1], offset: ?>> to memref<1x4096x16x1xf32, strided<[?, 16, 1, 1], offset: ?>>
          %subview_3 = memref.subview %subview_0[0, 0, 0, 0, 0] [1, 32, 4096, 16, 1] [1, 1, 1, 1, 1] : memref<1x32x4096x16x1xf32, strided<[16777216, 65536, 16, 1, 1], offset: ?>> to memref<32x4096x16x1xf32, strided<[65536, 16, 1, 1], offset: ?>>
          %base_buffer, %offset, %sizes:4, %strides:4 = memref.extract_strided_metadata %subview_2 : memref<1x4096x16x1xf32, strided<[?, 16, 1, 1], offset: ?>> -> memref<f32>, index, index, index, index, index, index, index, index, index
          %base_buffer_4, %offset_5, %sizes_6:4, %strides_7:4 = memref.extract_strided_metadata %subview_3 : memref<32x4096x16x1xf32, strided<[65536, 16, 1, 1], offset: ?>> -> memref<f32>, index, index, index, index, index, index, index, index, index
          %base_buffer_8, %offset_9, %sizes_10:4, %strides_11:4 = memref.extract_strided_metadata %subview_1 : memref<1x32x16x16xf32, strided<[65536, 256, 16, 1], offset: ?>> -> memref<f32>, index, index, index, index, index, index, index, index, index
          func.call @iree_uk_mmt4d(%base_buffer, %offset, %strides#0, %base_buffer_4, %offset_5, %c65536, %base_buffer_8, %offset_9, %c65536, %c1, %c32, %c4096, %c16_i32, %c16_i32, %c1_i32, %c1025_i32) : (memref<f32>, index, index, memref<f32>, index, index, memref<f32>, index, index, index, index, index, i32, i32, i32, i32) -> ()
        }
      }
    }
    return
  }
}
```

Run line:
```bash
iree-opt repro.mlir --iree-codegen-expand-strided-metadata
```

**Comment by qcolombet** [comment] 2023-10-04 09:46
The actual error is:
```
 note: remaining live use
          %subview_2 = memref.subview %cast[%arg0, %arg1, 0, 0, 0] [1, 1, 4096, 16, 1] [1, 1, 1, 1, 1] : memref<1x1x4096x16x1xf32, strided<[?, 65536, 16, 1, 1], offset: ?>> to memref<1x4096x16x1xf32, strided<[?, 16, 1, 1], offset: ?>>
                       ^
```

And AFAICT, the value is actually not use at the end of the rewrites, maybe some stall worklist?

Will look closer.

**Comment by qcolombet** [comment] 2023-10-04 13:11
The error message is misleading because it points to the location of the original instruction. The subview itself (`subview_2`) is actually properly eliminated.

What happens is we try to get rid of the `memref.extract_strided_metadata`s and we manage to do so with two of the three: `subview_1`, `subview_3`, which are both `extract_strided_metadata(subview(subview(subspan)))` thanks to the `extract_strided_metadata(subview)` and `extract_strided_metadata(subspan)` rewrite patterns.

Now the third chain comes from `extract_strided_metadata(subview(cast(subspan)))` and we don't have any rewrites for `extract_strided_metadata(cast)`.

My recommendation would be to add such pattern in MLIR upstream. MLIR already has support for `extract_strided_metadata(reinterpret_cast)` so adding `cast` should be fairly simple.

In the meantime, you can try running with `allow-unresolved=true`, which will allow `extract_strided_metadata` to live through this pass instead of stopping the pipeline. For LLVM proper that should work just fine since the lowering of `extract_strided_metadata` to LLVM is supported but I have no idea how well this plays with `subspan`.

I have other stuff I need to finish first, but I'll come back to the `cast` support if nobody beats me at it.

**Comment by qcolombet** [comment] 2023-10-05 08:58
Tentative patch at https://github.com/llvm/llvm-project/pull/68291

**Comment by qcolombet** [comment] 2023-10-05 09:01
@mariecwhite if you apply https://github.com/llvm/llvm-project/pull/68291 on top of your clone of `third_party/llvm-project`, you should be unblocked.

Otherwise, you'll have to wait for the patch to land in LLVM and then go through the integration.

**Comment by qcolombet** [comment] 2023-10-05 12:34
LLVM fix landed in LLVM upstream at https://github.com/llvm/llvm-project/commit/932dc9d8c4979f4f0aec33e2b9725a110ded8b61

**Comment by hanhanW** [comment] 2023-10-13 20:16
I verified that it's fixed, closing the issue

**Closed as completed by hanhanW** 2023-10-13 20:16 UTC
Labels: bug 🐞
