### ISSUE TITLE
iree compile for rocm (chip gfx942) exceeds shared memory limits

### ISSUE THREAD

**Issue by zjgarvey** [iree-org/iree#18195] opened 2024-08-13 00:20 UTC
### What happened?

Possibly related to <https://github.com/iree-org/iree/issues/17669>.

This issue causes a compilation fail for model "migraphx_cadene__resnext101_64x4di1" but not for "migraphx_cadene__resnext101_64x4di16". 

### Steps to reproduce your issue

Simplest reproducing compile command: 
```
iree-compile --iree-hal-target-backends="rocm" --iree-rocm-target-chip=gfx942 repro.mlir -o some.vmfb
```
on the elided and slightly smaller repro in this [gist](https://gist.github.com/zjgarvey/c1f081ae2d15b68227438f9d1b2dafab).
Full onnx model is available publicly on our Azure storage, so you can always run the whole e2e testing from the test suite (set up in alt_e2eshark). 

### What component(s) does this issue relate to?

Compiler

### Version information

<https://github.com/iree-org/iree/commit/76eb9c18f812db75bbe525b3de3bf478eaa05693>

### Additional context

Similar issues occur in other models. I'll try to post updates here.

**Comment by nirvedhmeshram** [comment] 2024-08-13 19:36
So (atleast one) offending dispatch is a  matmul M,N,K (1024,196, 1024) + elementwise. This is getting lowered through the  `LLVMGPUMatmulSimt`  where the shared memory usage issue is happening, without the elementwise its the same pipeline but it does go through. Anyway, wondering if this should use some padtointrinsic effort and go to `LLVMGPUVectorDistribute` instead which is what I see if I change N from 196 to 224?

**Comment by nirvedhmeshram** [comment] 2024-08-14 14:35
@zjgarvey the reported issue is fixed with https://github.com/iree-org/iree/pull/18212
but now I am seeing the following crash
```
iree-compile: iree/compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/ArchiveWriter.cpp:390: std::optional<ZIPFileRef> mlir::iree_compiler::IREE::VM::appendZIPFileToStream(std::string, uint64_t, uint64_t, std::function<LogicalResult (llvm::raw_ostream &)>, llvm::raw_ostream &): Assertion `fileRef.totalLength == fileLength && "declared length mismatch"' failed.
Please report issues to https://github.com/iree-org/iree/issues and include the crash backtrace.
Stack dump:
0.	Program arguments: iree-compile /home/nmeshram/sdxl-scripts/fp16-model/../../shared_memory_issue.mlir --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx942 -o /home/nmeshram/sdxl-scripts/fp16-model/tmp/prompt_encoder_working.vmfb --iree-hal-dump-executable-sources-to=sources/migraph1 --iree-hal-dump-executable-binaries-to=binaries/migraph1 --iree-hal-dump-executable-benchmarks-to=benchmarks/migraph1
 #0 0x000072ce30cca007 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/nmeshram/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:13
 #1 0x000072ce30cc8240 llvm::sys::RunSignalHandlers() /home/nmeshram/iree/third_party/llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #2 0x000072ce30cca6ca SignalHandler(int) /home/nmeshram/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #3 0x000072ce2a242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000072ce2a2969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x000072ce2a242476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x000072ce2a2287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x000072ce2a22871b (/lib/x86_64-linux-gnu/libc.so.6+0x2871b)
 #8 0x000072ce2a239e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
 #9 0x000072ce30e25bd4 mlir::iree_compiler::IREE::VM::appendZIPFileToFD(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, unsigned long, unsigned long, std::function<llvm::LogicalResult (llvm::raw_ostream&)>, llvm::raw_fd_ostream&) /home/nmeshram/iree/compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/ArchiveWriter.cpp:438:3
#10 0x000072ce30e25bd4 mlir::iree_compiler::IREE::VM::appendZIPFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, unsigned long, unsigned long, std::function<llvm::LogicalResult (llvm::raw_ostream&)>, llvm::raw_ostream&) /home/nmeshram/iree/compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/ArchiveWriter.cpp:462:14
#11 0x000072ce30e24f09 std::_Function_base::~_Function_base() /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:243:11
#12 0x000072ce30e24f09 mlir::iree_compiler::IREE::VM::ZIPArchiveWriter::flush(mlir::iree_compiler::FlatbufferBuilder&) /home/nmeshram/iree/compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/ArchiveWriter.cpp:661:20
#13 0x000072ce30e1e037 llvm::LogicalResult::failed() const /home/nmeshram/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:43:43
#14 0x000072ce30e1e037 llvm::failed(llvm::LogicalResult) /home/nmeshram/iree/third_party/llvm-project/llvm/include/llvm/Support/LogicalResult.h:71:58
#15 0x000072ce30e1e037 mlir::iree_compiler::IREE::VM::translateModuleToBytecode(mlir::iree_compiler::IREE::VM::ModuleOp, mlir::iree_compiler::IREE::VM::TargetOptions, mlir::iree_compiler::IREE::VM::BytecodeTargetOptions, llvm::raw_ostream&) /home/nmeshram/iree/compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp:690:7
#16 0x000072ce30e1e878 mlir::iree_compiler::IREE::VM::translateModuleToBytecode(mlir::ModuleOp, mlir::iree_compiler::IREE::VM::TargetOptions, mlir::iree_compiler::IREE::VM::BytecodeTargetOptions, llvm::raw_ostream&) /home/nmeshram/iree/compiler/src/iree/compiler/Dialect/VM/Target/Bytecode/BytecodeModuleTarget.cpp:708:10
#17 0x000072ce30c1fa3c mlir::iree_compiler::embed::(anonymous namespace)::Invocation::outputVMBytecode(mlir::iree_compiler::embed::(anonymous namespace)::Output&) /home/nmeshram/iree/compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp:0:0
#18 0x000072ce30c1fa3c ireeCompilerInvocationOutputVMBytecode /home/nmeshram/iree/compiler/src/iree/compiler/API/Internal/CompilerDriver.cpp:1533:28
#19 0x000072ce30e3f76d mlir::iree_compiler::runIreecMain(int, char**)::$_2::operator()(iree_compiler_source_t*) const /home/nmeshram/iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:0:21
#20 0x000072ce30e3ee41 mlir::iree_compiler::runIreecMain(int, char**) /home/nmeshram/iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:0:10
#21 0x000072ce2a229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#22 0x000072ce2a229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#23 0x0000570ece3c66b5 _start (/home/nmeshram/iree-build/tools/iree-compile+0x16b5)
```
I can investigate this further if needed but can you confirm that this is a real issue and not something with the elided repro?

**Comment by benvanik** [comment] 2024-08-14 15:04
it's because of your input - I'm surprised MLIR even parses that - if you want to elide values then you should use `dense_resource<__elided__>` - just removing the referenced resources will lead to issues.

**Comment by nirvedhmeshram** [comment] 2024-08-14 15:08
> it's because of your input - I'm surprised MLIR even parses that - if you want to elide values then you should use `dense_resource<__elided__>` - just removing the referenced resources will lead to issues.

Thanks, that makes sense. Closing this issue as the root cause is solved.

**Closed as completed by nirvedhmeshram** 2024-08-14 15:08 UTC
Labels: bug 🐞, codegen/rocm
