### ISSUE TITLE
[gpu][regression]: 'func.func' op failed to distribute

### ISSUE THREAD

**Issue by pdhirajkumarprasad** [iree-org/iree#18876] opened 2024-10-23 17:31 UTC
### What happened?

We have regression in iree on 20241015.1047 @ 7622770c3647cd902546fb23a831e967ee1ccf3e for given IR

```mlir
module {
  func.func @main_graph(%arg1: !torch.vtensor<[1,64,112,112],f32> , %arg2: !torch.vtensor<[1,128,56,56],f32>, %arg3: !torch.vtensor<[64,64,3,3],f32>, %arg4: !torch.vtensor<[64],f32> , %arg5: !torch.vtensor<[128,64,1,1],f32>, %arg6: !torch.vtensor<[128],f32>) -> !torch.vtensor<[1,128,56,56],f32>   attributes {torch.onnx_meta.ir_version = 8 : si64, torch.onnx_meta.opset_version = 21 : si64, torch.onnx_meta.opset_versions = {ai.onnx.contrib = 1 : si64, ai.onnx.ml = 4 : si64, ai.onnx.preview.training = 1 : si64, ai.onnx.training = 1 : si64, com.microsoft = 1 : si64, com.microsoft.experimental = 1 : si64, com.microsoft.nchwc = 1 : si64, org.pytorch.aten = 1 : si64}, torch.onnx_meta.producer_name = "vai_q_onnx", torch.onnx_meta.producer_version = "1.17.0+43059a7"} {
    %1 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<0> : tensor<si8>} : () -> !torch.vtensor<[],si8> 
    %2 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.562500e-02> : tensor<f32>} : () -> !torch.vtensor<[],f32> 
    %3 = torch.operator "onnx.QuantizeLinear"(%arg2, %2, %1) : (!torch.vtensor<[1,128,56,56],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1,128,56,56],si8> 
    %4 = torch.operator "onnx.Conv"(%arg1, %arg3, %arg4) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 1 : si64, torch.onnx.kernel_shape = [3 : si64, 3 : si64], torch.onnx.pads = [1 : si64, 1 : si64, 1 : si64, 1 : si64], torch.onnx.strides = [2 : si64, 2 : si64]} : (!torch.vtensor<[1,64,112,112],f32>, !torch.vtensor<[64,64,3,3],f32>, !torch.vtensor<[64],f32>) -> !torch.vtensor<[1,64,56,56],f32> 
    %5 = torch.operator "onnx.DequantizeLinear"(%3, %2, %1) : (!torch.vtensor<[1,128,56,56],si8>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1,128,56,56],f32> 
    %6 = torch.operator "onnx.Relu"(%4) : (!torch.vtensor<[1,64,56,56],f32>) -> !torch.vtensor<[1,64,56,56],f32> 
    %7 = torch.operator "onnx.Conv"(%6, %arg5, %arg6) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 1 : si64, torch.onnx.kernel_shape = [1 : si64, 1 : si64], torch.onnx.pads = [0 : si64, 0 : si64, 0 : si64, 0 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,64,56,56],f32>, !torch.vtensor<[128,64,1,1],f32>, !torch.vtensor<[128],f32>) -> !torch.vtensor<[1,128,56,56],f32> 
    %8 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<0> : tensor<si8>} : () -> !torch.vtensor<[],si8> 
    %9 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.562500e-02> : tensor<f32>} : () -> !torch.vtensor<[],f32> 
    %10 = torch.operator "onnx.QuantizeLinear"(%7, %9, %8) : (!torch.vtensor<[1,128,56,56],f32>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1,128,56,56],si8> 
    %11 = torch.operator "onnx.DequantizeLinear"(%10, %9, %8) : (!torch.vtensor<[1,128,56,56],si8>, !torch.vtensor<[],f32>, !torch.vtensor<[],si8>) -> !torch.vtensor<[1,128,56,56],f32> 
    %12 = torch.operator "onnx.Add"(%11, %5) : (!torch.vtensor<[1,128,56,56],f32>, !torch.vtensor<[1,128,56,56],f32>) -> !torch.vtensor<[1,128,56,56],f32> 
    %13 = torch.operator "onnx.Relu"(%12) : (!torch.vtensor<[1,128,56,56],f32>) -> !torch.vtensor<[1,128,56,56],f32> 
    return %13 : !torch.vtensor<[1,128,56,56],f32>
  }
}

```

it works fine with 20241014.1046 @ d7378bb7299bc558a09216559dc4b4fbf5cb59ef 

 error: 'func.func' op failed to distribute

### Steps to reproduce your issue

command:  

```
iree-compile --iree-hal-target-backends=rocm --iree-hip-target=gfx942 model.torch_onnx.mlir
```

### What component(s) does this issue relate to?

Compiler

**Comment by nirvedhmeshram** [comment] 2024-10-23 20:42
[Here](https://gist.github.com/nirvedhmeshram/c2ff1a0d38f56627b5da6a348f2be274) is a single dispatch that can repro the issue
```
iree-compile --iree-hal-target-backends=rocm --iree-hip-target=gfx942 single_dispatch.mlir
```
[Here](https://gist.github.com/nirvedhmeshram/c74175b09e266a957832095943e5a45f) is the IR dump, It fails in vector distribution @raikonenfnu @Groverkss

**Comment by raikonenfnu** [comment] 2024-10-24 00:53
I have a fix for it, there was some issue with the old bump

**Comment by nirvedhmeshram** [comment] 2024-10-25 16:04
The issue is solved with PR from @raikonenfnu , however fyi, the model didnt compile due to this different error
`error: 'func.func' op uses 873872 bytes of shared memory; exceeded the limit of 65536 bytes` in a different dispatch. It is becuase the SIMT pipeline (that we are trying to deprecate) choose some fairly big tile sizes perhaps for the elementwise that followed the matmul in the dispatch. We have similar bug open already https://github.com/iree-org/iree/issues/18603 so closing this one.

**Closed as completed by nirvedhmeshram** 2024-10-25 16:04 UTC
Labels: bug 🐞, regression

**Comment by nirvedhmeshram** [comment] 2024-10-25 16:45
Opened an issue tracking the next failure in the model as its a diffrerent IR then the ones we are currently tracking https://github.com/iree-org/iree/issues/18905
