### ISSUE TITLE
Model applying dropout twice causes index out of bounds assertion error in the Stream dialect

### ISSUE THREAD

**Issue by phoenix-meadowlark** [iree-org/iree#11201] opened 2022-11-17 22:23 UTC
### What happened?

A model which applies dropout twice causes the following LLVM assertion error in the Stream dialect when compiling to `llvm-cpu` or `vmvx`:

```
iree-compile: iree/third_party/llvm-project/llvm/include/llvm/ADT/SmallVector.h:294:
  llvm::SmallVectorTemplateCommon::reference llvm::SmallVectorTemplateCommon<unsigned long>::operator[](llvm::SmallVectorTemplateCommon::size_type) [T = unsigned long]: Assertion `idx < size()' failed.
```

This may be related to the fact that a while-loop is used, but the error only occurs when dropout is also applied outside of the loop. The error also only occurs when the input rank is > 2 and for only for specific input shapes.

### Steps to reproduce your issue

This can be reproduced using the following MLIR file: [`double_dropout.mlir`](https://gist.github.com/phoenix-meadowlark/d2abfb322f46b73bd4167d71a867bfc8)

```shell
iree-compile \
  --iree-hal-target-backends=llvm-cpu \
  --iree-input-type=mhlo \
  /tmp/double_dropout.mlir \
  -o /tmp/double_dropout.vmfb
```

Full error:

```
iree-compile: iree/third_party/llvm-project/llvm/include/llvm/ADT/SmallVector.h:294: llvm::SmallVectorTemplateCommon::reference llvm::SmallVectorTemplateCommon<unsigned long>::operator[](llvm::SmallVectorTemplateCommon::size_type) [T = unsigned long]: Assertion `idx < size()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=mhlo /tmp/double_dropout.mlir -o /tmp/double_dropout.vmfb
 #0 0x000055976681a853 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:569:13
 #1 0x0000559766818ab0 llvm::sys::RunSignalHandlers() iree/third_party/llvm-project/llvm/lib/Support/Signals.cpp:105:18
 #2 0x000055976681abba SignalHandler(int) iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #3 0x00007fdc84c3daa0 (/lib/x86_64-linux-gnu/libc.so.6+0x3daa0)
 #4 0x00007fdc84c8957c __pthread_kill_implementation ./nptl/./nptl/pthread_kill.c:44:76
 #5 0x00007fdc84c3da02 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #6 0x00007fdc84c28469 abort ./stdlib/./stdlib/abort.c:81:7
 #7 0x00007fdc84c28395 _nl_load_domain ./intl/./intl/loadmsgcat.c:1177:9
 #8 0x00007fdc84c36ab2 (/lib/x86_64-linux-gnu/libc.so.6+0x36ab2)
 #9 0x0000559764bfcb90 mlir::iree_compiler::IREE::Stream::partitionStreamableOpsReference(mlir::iree_compiler::IREE::Stream::PartitioningConfigAttr, mlir::Block*) iree/compiler/src/iree/compiler/Dialect/Stream/Analysis/Partitioning/ReferencePartitioning.cpp:0:0
#10 0x0000559764bf8a79 mlir::iree_compiler::IREE::Stream::partitionStreamableOps(mlir::iree_compiler::IREE::Stream::PartitioningConfigAttr, mlir::Block*) iree/compiler/src/iree/compiler/Dialect/Stream/Analysis/Partitioning.cpp:172:3
#11 0x0000559764b8e332 llvm::SmallVectorBase<unsigned int>::empty() const iree/third_party/llvm-project/llvm/include/llvm/ADT/SmallVector.h:94:46
#12 0x0000559764b8e332 mlir::iree_compiler::IREE::Stream::PartitionSet::empty() const iree/compiler/src/iree/compiler/Dialect/Stream/Analysis/Partitioning.h:54:42
#13 0x0000559764b8e332 mlir::iree_compiler::IREE::Stream::(anonymous namespace)::ScheduleExecutionPass::runOnOperation() iree/compiler/src/iree/compiler/Dialect/Stream/Transforms/ScheduleExecution.cpp:241:24
#14 0x00005597664cb6a1 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:0:11
#15 0x00005597664cbc98 mlir::LogicalResult::failed() const iree/third_party/llvm-project/mlir/include/mlir/Support/LogicalResult.h:44:33
#16 0x00005597664cbc98 mlir::failed(mlir::LogicalResult) iree/third_party/llvm-project/mlir/include/mlir/Support/LogicalResult.h:72:58
#17 0x00005597664cbc98 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:529:9
#18 0x00005597664cd298 std::vector<std::atomic<bool>, std::allocator<std::atomic<bool> > >::operator[](unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_vector.h:1124:25
#19 0x00005597664cd298 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14::operator()(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&) const iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:754:5
#20 0x00005597664cd298 mlir::LogicalResult mlir::failableParallelForEach<__gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14&>(mlir::MLIRContext*, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, __gnu_cxx::__normal_iterator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> > >, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14&) iree/third_party/llvm-project/mlir/include/mlir/IR/Threading.h:46:18
#21 0x00005597664cd298 mlir::LogicalResult mlir::failableParallelForEach<std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> >&, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14&>(mlir::MLIRContext*, std::vector<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo, std::allocator<mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo> >&, mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::$_14&) iree/third_party/llvm-project/mlir/include/mlir/IR/Threading.h:92:10
#22 0x00005597664cd298 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:759:14
#23 0x00005597664cb6da mlir::detail::OpToOpPassAdaptor::runOnOperation(bool) iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:0:5
#24 0x00005597664cb6da mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:463:14
#25 0x00005597664cbc98 mlir::LogicalResult::failed() const iree/third_party/llvm-project/mlir/include/mlir/Support/LogicalResult.h:44:33
#26 0x00005597664cbc98 mlir::failed(mlir::LogicalResult) iree/third_party/llvm-project/mlir/include/mlir/Support/LogicalResult.h:72:58
#27 0x00005597664cbc98 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:529:9
#28 0x00005597664ce0bb mlir::PassManager::run(mlir::Operation*) iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:0:0
#29 0x0000559761dbfdd6 mlir::LogicalResult::failed() const iree/third_party/llvm-project/mlir/include/mlir/Support/LogicalResult.h:44:33
#30 0x0000559761dbfdd6 mlir::failed(mlir::LogicalResult) iree/third_party/llvm-project/mlir/include/mlir/Support/LogicalResult.h:72:58
#31 0x0000559761dbfdd6 mlir::iree_compiler::runIreecMain(int, char**)::$_3::operator()(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >, llvm::raw_ostream&) const iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:285:9
#32 0x0000559761dbeb89 mlir::iree_compiler::runIreecMain(int, char**) iree/compiler/src/iree/compiler/Tools/iree_compile_lib.cc:336:16
#33 0x00007fdc84c2920a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#34 0x00007fdc84c292bc call_init ./csu/../csu/libc-start.c:128:20
#35 0x00007fdc84c292bc __libc_start_main ./csu/../csu/libc-start.c:376:5
#36 0x0000559761dbd421 _start (iree_build/tools/iree-compile+0x2f00421)
[1]    560958 IOT instruction  iree-compile --iree-hal-target-backends=llvm-cpu --iree-input-type=mhlo  -o
```

### What component(s) does this issue relate to?

Compiler

### Version information

7b2e4ef995305b56776cfc2b8c7a1dec7f2ff176

**Comment by antiagainst** [comment] 2023-01-12 21:38
I tried the latest commit e937ab110dfdacb66146c269203239c44ba28dc3 and cannot reproduce this issue. Maybe it was fixed in some prior commits. @phoenix-meadowlark could you double check?

**Closed** 2023-01-17 23:40 UTC
Labels: bug 🐞, compiler/dialects
