### ISSUE TITLE
(Vulkan) iree-compile LLD issues with UNet after openxla#14656

### ISSUE THREAD

**Issue by monorimet** [iree-org/iree#15088] opened 2023-10-02 17:33 UTC
### What happened?

Hi,

I've started running into a compilation error with Stable Diffusion UNet with this patch https://github.com/openxla/iree/pull/14656.

The output log shows:
```
(shark.venv) PS C:\V\SHARK> iree-compile .\unet_dispatches\module_forward_dispatch_249.mlir -o unet_249.vmfb --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-util-zero-fill-elided-attrs --iree-vulkan-target-triple=rdna3-7900-windows --iree-flow-break-dispatch=@forward:249
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: C:\\V\\SHARK\\shark.venv\\Lib\\site-packages\\iree\\compiler\\tools\\..\\_mlir_libs\\iree-compile.exe .\\unet_dispatches\\module_forward_dispatch_249.mlir -o unet_249.vmfb --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-util-zero-fill-elided-attrs --iree-vulkan-target-triple=rdna3-7900-windows --iree-flow-break-dispatch=@forward:249
Exception Code: 0xC0000005
 #0 0x00007ffdbe087ddb ireeCompilerRunLldMain (C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll+0x1e17ddb)
 #1 0x00007ffdbc7b3a2f ireeCompilerRunLldMain (C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll+0x543a2f)
 #2 0x00007ffdbe5106e8 ireeCompilerRunLldMain (C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll+0x22a06e8)
 #3 0x00007ffdbe511b86 ireeCompilerRunLldMain (C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll+0x22a1b86)
 #4 0x00007ffdbe501ccd ireeCompilerRunLldMain (C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll+0x2291ccd)
 #5 0x00007ffdbe500392 ireeCompilerRunLldMain (C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll+0x2290392)
 #6 0x00007ffdbe50224c ireeCompilerRunLldMain (C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll+0x229224c)
 #7 0x00007ffdbe50114f ireeCompilerRunLldMain (C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll+0x229114f)
 #8 0x00007ffdbc7b2400 ireeCompilerRunLldMain (C:\V\SHARK\shark.venv\Lib\site-packages\iree\compiler\_mlir_libs\IREECompiler.dll+0x542400)
```
(truncated, can post full log if the addresses/rest of the stack trace is useful.)

I've tracked this down to a single dispatch which is given in the reproducer instructions.

FYI @MaheshRavishankar 

### Steps to reproduce your issue

```
wget https://storage.googleapis.com/shark-public/ean/module_forward_dispatch_249.mlir

gsutil cp gs://shark-public/ean/module_forward_dispatch_249.mlir

iree-compile module_forward_dispatch_249.mlir -o unet_249.vmfb --iree-input-type=tm_tensor --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-util-zero-fill-elided-attrs --iree-vulkan-target-triple=rdna3-7900-windows
```

### Version information

IREE @ 15ace7e2f687cbf5c7821cbb7f28e95a604452a2

**Comment by stellaraccident** [comment] 2023-10-02 18:01
Small nit: the fact that the stack trace says "LLD" doesn't mean this is LLD related. It is an artifact of the binaries being stripped and is most likely a general compilation crash.

**Comment by MaheshRavishankar** [comment] 2023-10-02 20:30
I think I know the issue here. Will fix it upstream...

**Comment by MaheshRavishankar** [comment] 2023-10-02 21:11
I decided to just revert https://github.com/openxla/iree/pull/15090 for now. I think I can fix it, but will require some more work....

**Comment by antiagainst** [comment] 2023-10-03 03:48
Thanks Mahesh! I'll still keep this issue open and assign to you for now then, given you'll fix the issue sometime later. (It would also be nice to document what the issue is, given it's not immediately obvious from the above.)

**Comment by MaheshRavishankar** [comment] 2023-10-03 03:53
Just to clarify, the reverted commit just uncovered the underlying issue and is not the root cause. Earlier the pass removed in that commit would collapse the two reduction dimensions into a single reduction dimension, the new pass missed a case, and let the two reduction dimensions through, which then triggers the failure in the SPIR-V backend. Ill try to fix the Flow level pass to get back on par, but that would just again cover the backend issue.
Fine to assign to me for now.

**Comment by antiagainst** [comment] 2023-10-03 04:14
I see. Yeah we should take a look and fix the underlying SPIR-V issue too then. Not immediate anymore though.

**Comment by antiagainst** [comment] 2023-10-03 05:21
After taking a closer look this is actually the same issue as https://github.com/openxla/iree/issues/15078. So closing this one to avoid duplication.

**Closed as completed by antiagainst** 2023-10-03 05:21 UTC
Labels: bug 🐞, codegen, codegen/spirv
