### ISSUE TITLE
Scope memory effects to operands

### ISSUE THREAD

**Issue by stellaraccident** [iree-org/iree#9242] opened 2022-05-28 00:12 UTC
We have several stateful ops that declare memory effects, and we typically add these at the op level. However, this can block various optimizations by being too broad (i.e. not allowing dce of cycles involving the same values).

I learned the other day from Jeff/River that this can be better scoped. Example here: https://github.com/llvm/llvm-project/blob/2a5d5078d5dadb1aaa4487c89a92c91a98e2ed12/mlir/test/mlir-tblgen/op-side-effects.td#L17

We should likely update any ops with MemRead or MemWrite traits accordingly.

**Comment by stellaraccident** [comment] 2022-05-28 00:12
@benvanik

**Comment by ScottTodd** [comment] 2022-05-28 00:16
This sounds similar to https://github.com/google/iree/issues/1088 and https://github.com/google/iree/issues/1124. Those issues are really old though, so I bet the upstream infrastructure has matured quite a bit since then :)

**Comment by benvanik** [comment] 2022-05-28 00:19
yep, duplicate of #1124 but the new example is useful. A good task anyone should be able to pick up.

**Comment by benvanik** [comment] 2022-10-24 17:10
Closing in favor of #1124.

**Closed by benvanik** 2022-10-24 17:10 UTC
Labels: compiler/dialects
