### ISSUE TITLE
IREE model gives wrong result 

### ISSUE THREAD

**Issue by sergiuiacob1** [iree-org/iree#10691] opened 2022-10-07 11:34 UTC
### What happened?

I have a `jax.numpy` function computing mean on columns on a 2D tensor, but IREE does not give the right results.

```
building this func
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
running this func on Traced<ShapedArray(float32[2,8])>with<DynamicJaxprTrace(level=0/1)>
running this func on Traced<ShapedArray(float32[2,8])>with<DynamicJaxprTrace(level=1/0)>
[[ 5.  6.  7.  8.  9. 10. 11. 12.]]
[[ 5. inf inf inf  9. inf inf inf]]
Traceback (most recent call last):
  File "/home/ubuntu/shoreline/python/ceva.py", line 75, in <module>
    assert jnp.allclose(jax_result, iree_result)
AssertionError
```

The output comes from the below script.

### Steps to reproduce your issue

Run the script below. Assertion should pass. It does not, however.

```
import jax

import iree.compiler
import iree.compiler.tools.xla
import iree.runtime as ireert

import numpy as np
import jax.numpy as jnp


def build_group_avg():
    print("building this func")

    def _f(x):
        return jnp.nanmean(x, axis=0, keepdims=True)

    def __inner__(data):
        print(f"running this func on {data}")
        # vmap will apply the mean to each column
        f = jax.vmap(_f, in_axes=1, out_axes=1)
        return f(data)

    return __inner__



def aot(function, static_argnums, *args, **options):
    """Traces and compiles a function, flattening the input args.

    This is intended to be a lower-level interface for compiling a JAX function to
    IREE without setting up the runtime bindings to use it within Python. A common
    usecase for this is compiling to Android (and similar targets).

    Args:
      function: The function to compile.
      args: The inputs to trace and compile the function for.
      **kwargs: Keyword args corresponding to xla.ImportOptions or CompilerOptions
    """
    xla_comp = jax.xla_computation(function, static_argnums=static_argnums)(*args)
    hlo_proto = xla_comp.as_serialized_hlo_module_proto()
    return iree.compiler.tools.xla.compile_str(hlo_proto, input_type=iree.compiler.InputType.XLA, **options)



_DYLIB_CONFIG, _VM_INSTANCE = None, None

def load_iree_binary(pipeline_bytes: bytes):
    """Loads a compiled pipeline using IREE"""
    global _DYLIB_CONFIG, _VM_INSTANCE
    if not _DYLIB_CONFIG:
        # lazy initialization – ensures the config is created in the context of the calling process
        _DYLIB_CONFIG = ireert.Config("local-task")
    if not _VM_INSTANCE:
        _VM_INSTANCE = ireert.VmInstance()

    vm_module = ireert.VmModule.from_flatbuffer(_VM_INSTANCE, pipeline_bytes)
    module_object = ireert.load_vm_module(vm_module, _DYLIB_CONFIG)
    return module_object["main"]  # the compiled function to be ran



ii = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16]]).astype(np.float32)
f = build_group_avg()

f_jitted = jax.jit(f)
jax_result = np.array(f_jitted(ii))

compiled = aot(f, [], ii, target_backends=["llvm-cpu"])
ireefunc = load_iree_binary(compiled)
iree_result = np.array(ireefunc(ii))

print(jax_result)
print(iree_result)

assert jnp.allclose(jax_result, iree_result)
```

### What component(s) does this issue relate to?

Frontends, Python, Runtime

### Version information

```
jax==0.3.17
jaxlib==0.3.15
-f https://github.com/iree-org/iree/releases/expanded_assets/candidate-20220902.254
--extra-index-url https://github.com/iree-org/iree/releases/expanded_assets/candidate-20220902.254
iree-compiler
iree-runtime
iree-tools-tf
iree-tools-tflite
iree-tools-xla
```

### Additional context

Ran on Ubuntu with x86_64 cpu.

**Comment by sergiuiacob1** [comment] 2022-10-07 12:25
Changing target backend from `llvm-cpu` to `vmvx` provides correct result for the above. But if I change input to
```
ii = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14, 15, 16], [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan,]]).astype(np.float32)
```

Then the result is
```
building this func
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
running this func on Traced<ShapedArray(float32[3,8])>with<DynamicJaxprTrace(level=0/1)>
running this func on Traced<ShapedArray(float32[3,8])>with<DynamicJaxprTrace(level=1/0)>
[[ 5.  6.  7.  8.  9. 10. 11. 12.]]
[[nan nan nan nan nan nan nan nan]]
Traceback (most recent call last):
  File "/home/ubuntu/shoreline/python/ceva.py", line 75, in <module>
    assert jnp.allclose(jax_result, iree_result)
AssertionError
```

**Comment by sergiuiacob1** [comment] 2022-10-10 15:22
@GMNGeoffrey could you give an initial assessment for this issue, please? It's currently a blocker and I'm trying to figure out the following steps. Or maybe tag somebody who has more context for this, it would help a ton. Thank you!!

**Comment by jpienaar** [comment] 2022-10-10 22:29
We are looking at it, but no status update yet.

**Comment by rsuderman** [comment] 2022-10-10 23:45
Are you testing entirely using `inf`?  Both `jax` and `numpy` treat `inf` and `-inf` as non-NaN values, meaning setting an `inf` is not the same as setting a nan value. When trying to replicate this failure I see identical results comparing the iree cpu backend to jax's default backend.

**Comment by rsuderman** [comment] 2022-10-11 00:17
It is possible this is related to how you are generating your `mhlo-ir`. We generally don't support the proto importer anymore as JAX can directly generate `mhlo` now. Attaching a version that does not roundtrip to a proto and it appears to work correctly.

[output2.py.zip](https://github.com/iree-org/iree/files/9749891/output2.py.zip)

**Comment by aaron-schneider** [comment] 2022-10-11 16:01
@rsuderman - Since you're assigned and this has a marked priority, can we remove the `awaiting-triage` label?

**Comment by rsuderman** [comment] 2022-10-11 17:02
> @rsuderman - Since you're assigned and this has a marked priority, can we remove the `awaiting-triage` label?

Removed

**Comment by jpienaar** [comment] 2022-10-11 17:12
@rsuderman could you check with that release too? (given its currently marked as stable, we might want to downgrade it in that case).

**Comment by rsuderman** [comment] 2022-10-11 18:13
It appears this release head has an error for this reduction. I would guess that the NaN comparison is not working as intended.

**Comment by sergiuiacob1** [comment] 2022-10-12 09:12
`20220902.254` is marked as stable and I don't see a newer one. Is another stable version coming out? If so, do you know when?
I'd like to avoid using a nightly as it can have unexpected behaviour.

@rsuderman in that case, can my example be added as a unit test for the following releases?

**Comment by jpienaar** [comment] 2022-10-12 14:06
Yes we have roughly monthly cadence. https://github.com/iree-org/iree/releases/tag/candidate-20220930.282 is the one currently being evaluated.

**Comment by sergiuiacob1** [comment] 2022-10-19 18:00
> Yes we have roughly monthly cadence. https://github.com/iree-org/iree/releases/tag/candidate-20220930.282 is the one currently being evaluated.

@jpienaar I confirm that `candidate-20220930.282` does give the correct results.
I will let you decide when this issue should be closed.

**Comment by jpienaar** [comment] 2022-10-19 22:01
Thanks, we are running behind in completing some of the processes wrt new release. For now please feel free to use it. Hope to get new stable release out soon but hitting some procedural issues.

**Comment by jpienaar** [comment] 2022-12-30 16:36
That version was released (even if release post that got delayed again 🤒  ). With OpenXLA & PJRT work JAX unit tests will be running these a lot more, so closing.

**Closed by jpienaar** 2022-12-30 16:36 UTC
Labels: bug 🐞, integrations/mhlo
