### ISSUE TITLE
CPU Compilation stucks at IREE::HAL::SerializeTargetExecutablesPass

### ISSUE THREAD

**Issue by vivekkhandelwal1** [iree-org/iree#14741] opened 2023-08-18 16:05 UTC
### What happened?

During the compilation for the CPU backend, the iree-compile keeps on running without any termination.

### Steps to reproduce your issue

To reproduce the issue, run the following:
```
./build/tools/iree-compile --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary     --iree-hal-target-backends=llvm-cpu --mlir-print-debuginfo     --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host     --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64     --iree-vm-bytecode-module-strip-source-map=false --iree-util-zero-fill-elided-attrs     --iree-vm-target-truncate-unsupported-floats --iree-codegen-check-ir-before-llvm-conversion=false   --iree-opt-const-expr-hoisting=false     --iree-consteval-jit-debug=true   --iree-stream-resource-max-allocation-size=3221225472 
```
over the given IR: 
```
hal.executable public @forward_dispatch_7 {
  hal.executable.variant public @embedded_elf_x86_64, target = <"llvm-cpu", "embedded-elf-x86_64", {cpu = "generic", cpu_features = "+prfchw,-cldemote,+avx,+aes,+sahf,+pclmul,-xop,+crc32,+xsaves,-avx512fp16,-sm4,+sse4.1,-avx512ifma,+xsave,-avx512pf,+sse4.2,-tsxldtrk,-ptwrite,-widekl,-sm3,+invpcid,+64bit,+xsavec,-avx512vpopcntdq,+cmov,-avx512vp2intersect,+avx512cd,+movbe,-avxvnniint8,-avx512er,-amx-int8,-kl,-sha512,-avxvnni,+rtm,+adx,+avx2,-hreset,-movdiri,-serialize,-vpclmulqdq,+avx512vl,-uintr,+clflushopt,-raoint,-cmpccxadd,+bmi,-amx-tile,+sse,-gfni,-avxvnniint16,-amx-fp16,+xsaveopt,+rdrnd,+avx512f,-amx-bf16,-avx512bf16,+avx512vnni,+cx8,+avx512bw,+sse3,-pku,+fsgsbase,-clzero,-mwaitx,-lwp,+lzcnt,-sha,-movdir64b,-wbnoinvd,-enqcmd,-prefetchwt1,-avxneconvert,-tbm,-pconfig,-amx-complex,+ssse3,+cx16,+bmi2,+fma,+popcnt,-avxifma,+f16c,-avx512bitalg,-rdpru,+clwb,+mmx,+sse2,+rdseed,-avx512vbmi2,-prefetchi,-rdpid,-fma4,-avx512vbmi,-shstk,-vaes,-waitpkg,-sgx,+fxsr,+avx512dq,-sse4a", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 64 : index, target_triple = "x86_64-unknown-unknown-eabi-elf", ukernels = false}> {
    hal.executable.export public @forward_dispatch_7_generic_1x1x4096x32x128_f16 ordinal(0) layout(#hal.pipeline.layout<push_constants = 5, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer, ReadOnly>, <2, storage_buffer, ReadOnly>, <3, storage_buffer>]>]>) {
    ^bb0(%arg0: !hal.device loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))):
      %x, %y, %z = flow.dispatch.workgroup_count_from_slice  loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
      hal.return %x, %y, %z : index, index, index loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
    } loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
    builtin.module {
      func.func @forward_dispatch_7_generic_1x1x4096x32x128_f16() {
        %cst = arith.constant 0.000000e+00 : f16 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":769:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %0 = hal.interface.constant.load[0] : i32 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":923:21 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %1 = hal.interface.constant.load[1] : i32 loc(fused[callsite("../shark-vivekkhandelwal1/second_int4.mlir":698:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3), callsite("../shark-vivekkhandelwal1/second_int4.mlir":697:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3)])
        %2 = hal.interface.constant.load[2] : i32 loc(fused[callsite("../shark-vivekkhandelwal1/second_int4.mlir":698:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3), callsite("../shark-vivekkhandelwal1/second_int4.mlir":697:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3)])
        %3 = hal.interface.constant.load[3] : i32 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":917:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %4 = hal.interface.constant.load[4] : i32 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %5 = arith.index_castui %0 : i32 to index loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":923:21 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %6 = arith.index_castui %1 : i32 to index loc(fused[callsite("../shark-vivekkhandelwal1/second_int4.mlir":698:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3), callsite("../shark-vivekkhandelwal1/second_int4.mlir":697:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3)])
        %7 = arith.index_castui %2 : i32 to index loc(fused[callsite("../shark-vivekkhandelwal1/second_int4.mlir":698:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3), callsite("../shark-vivekkhandelwal1/second_int4.mlir":697:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3)])
        %8 = arith.index_castui %3 : i32 to index loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":917:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %9 = arith.index_castui %4 : i32 to index loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %10 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%5) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<4096x32x128xi4>> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":923:21 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %11 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%6) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<4096x32x1xf16>> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":698:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %12 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%7) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<4096x32x1xf16>> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":697:16 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %13 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%8) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<1x1x32x128xf16>> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":917:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %14 = hal.interface.binding.subspan set(0) binding(3) type(storage_buffer) alignment(64) offset(%9) : !flow.dispatch.tensor<writeonly:tensor<1x1x4096xf16>> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %15 = flow.dispatch.tensor.load %10, offsets = [0, 0, 0], sizes = [4096, 32, 128], strides = [1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<4096x32x128xi4>> -> tensor<4096x32x128xi4> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %16 = flow.dispatch.tensor.load %11, offsets = [0, 0, 0], sizes = [4096, 32, 1], strides = [1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<4096x32x1xf16>> -> tensor<4096x32x1xf16> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %17 = flow.dispatch.tensor.load %12, offsets = [0, 0, 0], sizes = [4096, 32, 1], strides = [1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<4096x32x1xf16>> -> tensor<4096x32x1xf16> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %18 = flow.dispatch.tensor.load %13, offsets = [0, 0, 0, 0], sizes = [1, 1, 32, 128], strides = [1, 1, 1, 1] : !flow.dispatch.tensor<readonly:tensor<1x1x32x128xf16>> -> tensor<1x1x32x128xf16> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %19 = tensor.empty() : tensor<1x1x4096xf16> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":797:10 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %20 = tensor.empty() : tensor<4096x32x128xf16> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":924:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %21 = linalg.fill ins(%cst : f16) outs(%19 : tensor<1x1x4096xf16>) -> tensor<1x1x4096xf16> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":925:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %22 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, 0)>, affine_map<(d0, d1, d2) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel"]} ins(%15, %16, %17 : tensor<4096x32x128xi4>, tensor<4096x32x1xf16>, tensor<4096x32x1xf16>) outs(%20 : tensor<4096x32x128xf16>) {
        ^bb0(%in: i4 loc("../shark-vivekkhandelwal1/second_int4.mlir":927:10), %in_0: f16 loc("../shark-vivekkhandelwal1/second_int4.mlir":927:19), %in_1: f16 loc("../shark-vivekkhandelwal1/second_int4.mlir":927:34), %out: f16 loc("../shark-vivekkhandelwal1/second_int4.mlir":927:49)):
          %24 = arith.extui %in : i4 to i32 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":928:15 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
          %25 = arith.uitofp %24 : i32 to f16 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":929:15 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
          %26 = arith.subf %25, %in_1 : f16 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":930:15 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
          %27 = arith.mulf %26, %in_0 : f16 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":931:15 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
          linalg.yield %27 : f16 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":932:7 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        } -> tensor<4096x32x128xf16> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":926:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        %23 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d3, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d2, d3, d4)>, affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction", "reduction"]} ins(%18, %22 : tensor<1x1x32x128xf16>, tensor<4096x32x128xf16>) outs(%21 : tensor<1x1x4096xf16>) {
        ^bb0(%in: f16 loc("../shark-vivekkhandelwal1/second_int4.mlir":935:10), %in_0: f16 loc("../shark-vivekkhandelwal1/second_int4.mlir":935:20), %out: f16 loc("../shark-vivekkhandelwal1/second_int4.mlir":935:35)):
          %24 = arith.mulf %in, %in_0 : f16 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":936:15 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
          %25 = arith.addf %24, %out : f16 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":937:15 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
          linalg.yield %25 : f16 loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":938:7 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        } -> tensor<1x1x4096xf16> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        flow.dispatch.tensor.store %23, %14, offsets = [0, 0, 0], sizes = [1, 1, 4096], strides = [1, 1, 1] : tensor<1x1x4096xf16> -> !flow.dispatch.tensor<writeonly:tensor<1x1x4096xf16>> loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
        return loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
      } loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
    } loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
  } loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))
} loc(callsite("../shark-vivekkhandelwal1/second_int4.mlir":934:11 at "../shark-vivekkhandelwal1/second_int4.mlir":26:3))

```

### What component(s) does this issue relate to?

Compiler

**Comment by antiagainst** [comment] 2023-08-18 20:51
~This is failing due to unit dims in `vector<1x8xf16>` and its appearance as loop carried values. We have had a host of such issues previously regarding the combination before. I think to properly fix this, we just need a new pattern to cast away leading unit dims for loop carried values.~

[Actually this is meant for #14740]

**Comment by vivekkhandelwal1** [comment] 2023-08-21 14:11
The issue still exists for the following dispatch:
```
#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d0)>
module {
  func.func @forward_dispatch_6_generic_Dx4096_f16xf32xf16(%arg0: tensor<1x?x4096xf32>, %arg1: tensor<?x4096xf16>) -> tensor<?x4096xf16> {
    %c1 = arith.constant 1 : index
    %cst = arith.constant 2.000000e+00 : f32
    %cst_0 = arith.constant 0.000000e+00 : f32
    %cst_1 = arith.constant 4.096000e+03 : f32
    %cst_2 = arith.constant 9.99999997E-7 : f32
    %c0 = arith.constant 0 : index
    %dim = tensor.dim %arg0, %c1 : tensor<1x?x4096xf32>
    %0 = tensor.empty(%dim) : tensor<?x4096xf16>
    %1 = tensor.empty(%dim) : tensor<?xf32>
    %2 = tensor.empty(%dim) : tensor<?x4096xf32>
    %3 = linalg.fill ins(%cst_0 : f32) outs(%1 : tensor<?xf32>) -> tensor<?xf32>
    %4 = linalg.generic {indexing_maps = [#map], iterator_types = ["parallel", "parallel"]} outs(%2 : tensor<?x4096xf32>) {
    ^bb0(%out: f32):
      %7 = linalg.index 0 : index
      %8 = linalg.index 1 : index
      %9 = arith.cmpi eq, %dim, %c1 : index
      %10 = arith.select %9, %c0, %7 : index
      %extracted = tensor.extract %arg0[%c0, %10, %8] : tensor<1x?x4096xf32>
      linalg.yield %extracted : f32
    } -> tensor<?x4096xf32>
    %5 = linalg.generic {indexing_maps = [#map, #map1], iterator_types = ["parallel", "reduction"]} ins(%4 : tensor<?x4096xf32>) outs(%3 : tensor<?xf32>) {
    ^bb0(%in: f32, %out: f32):
      %7 = math.powf %in, %cst : f32
      %8 = arith.addf %7, %out : f32
      linalg.yield %8 : f32
    } -> tensor<?xf32>
    %6 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%arg1, %5 : tensor<?x4096xf16>, tensor<?xf32>) outs(%0 : tensor<?x4096xf16>) {
    ^bb0(%in: f16, %in_3: f32, %out: f16):
      %7 = arith.divf %in_3, %cst_1 : f32
      %8 = arith.addf %7, %cst_2 : f32
      %9 = math.rsqrt %8 : f32
      %10 = arith.extf %in : f16 to f32
      %11 = arith.mulf %10, %9 : f32
      %12 = arith.truncf %11 : f32 to f16
      linalg.yield %12 : f16
    } -> tensor<?x4096xf16>
    return %6 : tensor<?x4096xf16>
  }
}
```

**Comment by Groverkss** [comment] 2023-08-21 18:24
I cannot reproduce for either of the dispatches you give. I tried with the `iree-compile` command given in your original issue. Maybe if the pipeline is actually stuck or is it just taking a long time to compile.

**Comment by vivekkhandelwal1** [comment] 2023-08-22 11:46
> I cannot reproduce for either of the dispatches you give. I tried with the `iree-compile` command given in your original issue. Maybe if the pipeline is actually stuck or is it just taking a long time to compile.

The issue exists with the SRT, not with the IREE.

**Comment by Groverkss** [comment] 2023-08-23 06:10
Could we file this issue on SRT instead then?

**Comment by Groverkss** [comment] 2023-08-25 09:34
Closing this since it's not an issue with IREE.

**Closed as completed by Groverkss** 2023-08-25 09:34 UTC
Labels: bug 🐞
