### ISSUE TITLE
Compiling to vulkan-SPIRV backend fails

### ISSUE THREAD

**Issue by gpetters94** [iree-org/iree#10501] opened 2022-09-21 21:19 UTC
### What happened?

Running the command `iree-compile --iree-input-type=tm_tensor --iree-hal-target-backends=vulkan-spirv --mlir-print-debuginfo --iree-util-zero-fill-elided-attrs opt.tmtensor.mlir > out.vmfb` segfaults after producing the following errors:

```
iree-compile: /home/gap/git/iree/third_party/llvm-project/mlir/lib/Conversion/MemRefToSPIRV/MemRefToSPIRV.cpp:459: virtual mlir::LogicalResult (anonymous namespace)::IntStoreOpPattern::matchAndRewrite(memref::StoreOp, mlir::OpConversionPattern<mlir::memref::StoreOp>::OpAdaptor, mlir::ConversionPatternRewriter &) const: Assertion `dstBits % srcBits == 0' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
iree-compile: /home/gap/git/iree/third_party/llvm-project/mlir/lib/Conversion/MemRefToSPIRV/MemRefToSPIRV.cpp:344: virtual mlir::LogicalResult (anonymous namespace)::IntLoadOpPattern::matchAndRewrite(memref::LoadOp, mlir::OpConversionPattern<mlir::memref::LoadOp>::OpAdaptor, mlir::ConversionPatternRewriter &) const: Assertion `dstBits % srcBits == 0' failed.
Aborted (core dumped)
```

### Steps to reproduce your issue

1. Run the iree-compile command

### What component(s) does this issue relate to?

Compiler

### Version information

5263ddeda8b44fa7e79a8a191c0b1297c06a7ecb

### Additional context

This arose while testing another issue where `iree-run-module` returned bad results on Vulkan, I'm not sure if they are related.

**Comment by gpetters94** [comment] 2022-09-21 21:21
Here's the [backtrace](https://github.com/iree-org/iree/files/9620464/gdb.txt)

**Comment by gpetters94** [comment] 2022-09-21 21:29
Working on uploading the MLIR, it's over 1GB.

**Comment by gpetters94** [comment] 2022-09-21 23:49
Okay, here's the [offending MLIR.](https://drive.google.com/file/d/1_9SkWbqrhQ-9hWRGLjfhjiV-Yh3666rf/view?usp=sharing)

**Comment by gpetters94** [comment] 2022-09-22 00:27
Okay, here's the [offending MLIR.](https://drive.google.com/file/d/17LM7UCf9Tbkvkf-qGMTHkI79B2TMhSJg/view?usp=sharing)

**Comment by antiagainst** [comment] 2022-09-23 00:15
Oh this is actually a gigantic model with a 2.5GB textual source file. :) The issue is actually we have i64 in the source model, and we are trying to compile towards a target that does not support it. (Note that if no `--iree-vulkan-target-triple=` or `--iree-vulkan-target-env=` is specified, we use the default of SwiftShader, for testing purposes. It does not support Int64.) For such cases we'd need to emulate i64 support. However, the current logic in SPIR-V for it is just problematic (See https://github.com/llvm/llvm-project/issues/57917); @kuhar is working on a more generic and robust solution there. Once that's done we can then compile it. 

The above assumes we must use i64 though. There are larger ongoing discussions (e.g., see https://github.com/iree-org/iree/issues/8826) as whether i64 is really needed for the wide range, or it's just the frontend default. 

To compile this now, you can try to give it a target that supports int64 natively, for example, `--iree-vulkan-target-triple=ampere-unknown-linux` (which is for NVIDIA GPUs).

**Comment by gpetters94** [comment] 2022-09-23 03:47
> Oh this is actually a gigantic model with a 2.5GB textual source file. :) The issue is actually we have i64 in the source model, and we are trying to compile towards a target that does not support it. (Note that if no `--iree-vulkan-target-triple=` or `--iree-vulkan-target-env=` is specified, we use the default of SwiftShader, for testing purposes. It does not support Int64.) For such cases we'd need to emulate i64 support. However, the current logic in SPIR-V for it is just problematic (See [llvm/llvm-project#57917](https://github.com/llvm/llvm-project/issues/57917)); @kuhar is working on a more generic and robust solution there. Once that's done we can then compile it.
> 
> The above assumes we must use i64 though. There are larger ongoing discussions (e.g., see #8826) as whether i64 is really needed for the wide range, or it's just the frontend default.
> 
> To compile this now, you can try to give it a target that supports int64 natively, for example, `--iree-vulkan-target-triple=ampere-unknown-linux` (which is for NVIDIA GPUs).

Ah, I see, makes sense. Should I close this issue in favor of adding a more general "add i64 support to SwiftShader"?

**Comment by antiagainst** [comment] 2022-09-23 14:39
We already have a tracking issue #8702 for i64 emulation. So I'd close this one for now. Thanks!

**Closed by antiagainst** 2022-09-23 14:39 UTC
Labels: bug 🐞, codegen/spirv
