### ISSUE TITLE
SHARK tests are not deterministic

### ISSUE THREAD

**Issue by hanhanW** [iree-org/iree#9853] opened 2022-07-20 16:55 UTC
I found that the SHARK tests are not deterministic. The inputs used for tests are different between runs. We should have fixed input data for the integration tests.

**Comment by GMNGeoffrey** [comment] 2022-07-20 20:23
@hanhanW please use the blank issue for filing generic issues. If you forget, please clean up all the boilerplate :-)

**Comment by powderluv** [comment] 2022-07-20 22:16
yes lets track this. @monorimet can you please take a look. And subscribe to the IREE github so I can assign it to you.

**Comment by monorimet** [comment] 2022-07-20 22:28
Inputs for PyTorch tests should be the same for each test case on one model. Do we want inputs to be the same across models as well (where applicable), or is this an issue with TensorFlow tests specifically?

If we're talking about TensorFlow, those tests will become deterministic once the tests are reworked to use .mlir and inputs downloaded from `gs://shark_tank/<modelname>/` (like we have for pytorch models). I'm not sure how long that will take us (I would expect it done by the end of the week), but I can put up a fix for the meantime.

**Comment by GMNGeoffrey** [comment] 2022-07-20 22:45
MLIR text isn't a stable format, so I'd be careful with that. We've had issues in the past where that sort of thing not stored in source is painful to update with syntax changes

**Comment by monorimet** [comment] 2022-07-20 22:55
We have a script to generate all of that data locally as well -- is it sufficient that we are able to easily generate and upload to `gs://shark_tank` a new set of compiler inputs for any SHARK-supported model if the need arises (i.e., upstream changes occur that would change the MLIR)?

**Comment by monorimet** [comment] 2022-07-20 23:07
Also, the TensorFlow inputs should be the same across runs (they're generated from a string that's hardcoded [here](https://github.com/nod-ai/SHARK/blob/main/tank/masked_lm_tf.py#L45))

@hanhanW I will take a look at tests for all frontends but please let me know if you're encountering this issue with a specific model/frontend.

**Comment by hanhanW** [comment] 2022-07-21 10:07
I observed it when running `LayoutLMModuleTest`. I still observed the same issue. Here is how I reproduce the issue:

```
# update SHARK repo -- attach at 3c2f8ef24341b0476944cb24d7fd79154fd22a90
$ git pull
# create a new venv
$ VENV_DIR=0721_venv IMPORTER=1 USE_IREE=1 ./setup_venv.sh
$ source 0721_venv/bin/activate

# Run two times
$ pytest --save_temps tank/tf/hf_masked_lm/layoutlm-base-uncased_tf_test.py::LayoutLMModuleTest::test_module_static_cpu
$ pytest --save_temps tank/tf/hf_masked_lm/layoutlm-base-uncased_tf_test.py::LayoutLMModuleTest::test_module_static_cpu
```

There will be two directories under `shark_tmp`. If we look into the `expected_out.txt`, we'll find that they are different. E.g.,

```
❯ head -n1 iree_tfsmbr9krai/expected_out.txt
[[[ 1.95667243e+00  1.97509766e+00  1.49286246e+00  7.99876928e-01

❯ head -n1 iree_tfst9ufel26/expected_out.txt
[[[-5.47550440e-01 -1.52990317e+00 -1.70632601e-01 -6.93688989e-01
```

**Comment by monorimet** [comment] 2022-07-21 16:30
This definitely suggests that there's something wrong with how we're getting the golden values (expected output), which adds up with the issues we were having with numerics earlier -- can you check the function inputs to see if they are the same? `diff -s iree_tfsmbr9krai/input1.txt iree_tfst9ufel26/input1.txt` should do the trick.

I'll bring this up in our sync today to make sure we have a plan on fixing those -- ideally by the end of the week we'll have our TensorFlow tests operating as intended.

**Comment by monorimet** [comment] 2022-07-21 18:16
I was able to reproduce this issue for LayoutLM. However, the expected outputs are consistent on some other models -- for example, the expected outputs between runs on bert-base-uncased from Tensorflow are identical (they still fail to validate against SHARK results, so there's probably another problem with LayoutLM).

I'm working on this as a first priority, and will update as soon as progress is made. Thanks for the help with repro.

**Comment by GMNGeoffrey** [comment] 2022-07-21 20:04
> We have a script to generate all of that data locally as well -- is it sufficient that we are able to easily generate and upload to `gs://shark_tank` a new set of compiler inputs for any SHARK-supported model if the need arises (i.e., upstream changes occur that would change the MLIR)?

If we're running something that reports commits as failed, especially if it happens on presubmit, we need to have something that can be updated via source code changes. It is otherwise impossible to test a commit with the new MLIR file without breaking tests that relied on the old MLIR file (from previous commits). It also makes the test a function of more than just the source code. Occasional network flakes and such are manageable (though I'd really like to isolate them into an initialization step that clearly doesn't report as a test failure), but something that can be updated out from under is isn't. In particular, I really don't want to put more burden on the LLVM integration process, which is already painful. That's the case where we're most likely to run into the need for updates. That said, we obviously can't be storing big input files in git. So I think order of preference would be:

1. A model expressible as a reasonable amount of source code (e.g. Python source)
2. A stable serialization format that we fetch from GCS (e.g. TFLite flatbuffers)
3. An unstable serialization format (e.g. MLIR files) stored in GCS *and indexed by version in some way*. The simplest indexing scheme I think would be a hash digest of the file itself, but something like the commit it was built from, or even just a monotonically increasing version number would be fine too. It is then possible to add a new version of the file to the storage without breaking anything and to update the source to point at this new version as a change to the source code. I still don't want that to be something that weighs heavily on the shoulders of integrators though, so updating needs to be straightforward. That means there's a quick skip they can run to point at "latest" versions or there's only one place to update and the thing to update it to is somewhat meaningful (like an LLVM commit hash iff the files are dependent solely on LLVM commit). The scripting could also *create* the latest version, if that's something can be done quickly. Otherwise, there would need to be some separate process to create the latest versions at least as often as needed so that they were already there when the person integrating LLVM needed them.

**Comment by monorimet** [comment] 2022-07-21 20:41
@GMNGeoffrey Thank you for the careful explanation. For IREE's use cases and especially testing purposes I see how this would make the LLVM integration harder to maintain, and would like to address this with our team to decide how to navigate this issue.

@hanhanW I have a pretty important update that might help diagnose the numerics issues for _all our TF hf_masked_lm model tests_. I noticed that even during CPU cases, TensorFlow was utilizing the A100 GPU to generate the model, inputs, and expected output for our tests.

If we establish `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"` before generating the huggingface masked_lm model (to hide the A100 from TensorFlow), all the static_cpu tests -- including LayoutLM -- passed, with our results within tolerance of the TF golden results.

Thus, there's probably some interaction between TensorFlow and CUDA (or the A100 specifically, since we don't have this issue without it) that introduces the numeric discrepancies in the results.

Is it also a possibility that certain optimizations happen in TensorFlow with the A100 that are not accurately reproduced in IREE?

I will keep investigating, but please let me know in the meantime if you have any insights based off of this update.

**Comment by GMNGeoffrey** [comment] 2022-07-21 22:26
> I noticed that even during CPU cases, TensorFlow was utilizing the A100 GPU to generate the model, inputs, and expected output for our tests.
> 
> If we establish `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"` before generating the huggingface masked_lm model (to hide the A100 from TensorFlow), all the static_cpu tests -- including LayoutLM -- passed, with our results within tolerance of the TF golden results.

Ah the classic problem that TensorFlow is always trying to do something with Cuda, no matter what you actually asked for

**Comment by hanhanW** [comment] 2022-07-22 04:08
SG, thanks for the investigations and detailed context! They might have some reasons for doing it, but I'd suggest to disable those fancy optimization at this moment. It should be an option to us, not always turn it on by default.

**Comment by monorimet** [comment] 2022-07-22 05:25
There are a few remaining problems with the masked_lm model tests that we are tracking in the SHARK issues, but this issue should be resolved by https://github.com/nod-ai/SHARK/pull/199.

**Comment by alliemartens** [comment] 2022-07-28 18:08
From today's meeting: @powderluv checking to see if this is resolved.

**Closed** 2022-08-04 17:54 UTC
Labels: bug 🐞, infrastructure
